Fixed receiver and motor tabs plot style
betaflight/betaflight-configurator pull request #2195
Opened 2020-10-03 09:31 UTC by Asizon

Fixed css style for Receiver and Motors tabs plots:

![image](https://user-images.githubusercontent.com/43983086/94988237-01d0cc80-056c-11eb-902d-a789eb077b2a.png)

2020-10-03 10:30 UTC, haslinghuis commented
Thanks. Looks much better now!

2020-10-03 10:35 UTC, haslinghuis requested changes

2020-10-03 10:35 UTC, haslinghuis commented on src/css/tabs/receiver.css
> +    height; 203px;
```suggestion
    height: 203px;
```

2020-10-03 10:38 UTC, Asizon commented on src/css/tabs/receiver.css
> +    height; 203px;
Ouch! Thanks for catch it

2020-10-03 15:05 UTC, McGiverGim approved these changes

2020-10-03 18:17 UTC, McGiverGim approved these changes

2020-10-04 10:06 UTC, mikeller approved these changes

2020-10-04 10:06 UTC, merged