Motor direction dialog for Dshot escs
betaflight/betaflight-configurator pull request #2296
Opened 2020-11-28 06:02 UTC by limonspb

A dialog to fix motor direction without necessity of going to blheli_s/32/jesc configurator.
Works through Dshot commands so appears only if Dshot protocol selected.
![image](https://user-images.githubusercontent.com/2925027/100494985-a30f7580-310c-11eb-9320-d5a71dc92fc6.png)
![image](https://user-images.githubusercontent.com/2925027/100495012-d6ea9b00-310c-11eb-9b9a-b1774f518c91.png)

Firmware changes pull request:

2020-11-28 06:14 UTC, Asizon commented on locales/en/messages.json
> +        "message": "Fix motor direction"
Good job Lemon lets try it, I think it should be named "Motor direction" like dialog tittle.

2020-11-28 07:39 UTC, Asizon commented
Tested @limonspb ! It works so good, only two things:
-Maybe autospin of 1200 is to high if we need to see the motor direction, can we made something to use 1100 or similar?
-An strange issue when click "Spin motor",  If you press it and move the mouse out of the dialog, you can release the mouse click and the motor keeps turning.

2020-11-28 07:42 UTC, Asizon commented
I forgot another point:
-Spin button hover seems ok, but normal and reverse buttons have a missing hover style action

2020-11-28 07:49 UTC, limonspb commented
> I forgot another point:
> -Spin button style seems ok when you click it, but normal and reverse buttons have a missing click style action

this is maybe something to think about...
None of the buttons in Configurator has style for when you click them.
I decided to add this "clicked" style for "spin motor" because it's a button user will push and keep pushing as long as he needs to spin a motor. Where as "direction normal/reversed" buttons are just normal buttons like every other button in the configurator.

2020-11-28 07:53 UTC, Asizon commented
ok @limonspb now I sew what happens with this, i can see that the other yeellow button around configurator have a hover style,This is why I have not seen the normal and reverse buttons intuitive.

2020-11-28 07:53 UTC, limonspb commented
> Tested @limonspb ! It works so good, only two things:
> -Maybe autospin of 1200 is to high if we need to see the motor direction, can we made something to use 1100 or similar?
> -An strange issue when click "Spin motor", If you press it and move the mouse out of the dialog, you can release the mouse click and the motor keeps turning.

@Asizon 
1. I think you are right about 1100. Because this is Dshot and 1100 should give some motor rotation speed anyway, shouldn't it?
2. I can't reproduce this on my windows. Could you please confirm? When i press and move the motor is still spinning, but it stops as soon as I release. Here is the code for that:
`        this._spinButton.on("mouseup **mouseleave**", () => {
            this._spinButton.removeClass("selected");
            this._spinMotor(-1);
        });`
as you can see there is "mouseleave"... Any ideas? Thanks!

2020-11-28 07:55 UTC, Asizon commented
> > Probado @limonspb ! Funciona muy bien, solo dos cosas: 
> > -Tal vez el giro automático de 1200 sea demasiado alto si necesitamos ver la dirección del motor, ¿podemos hacer algo para usar 1100 o similar? 
> > -Un problema extraño al hacer clic en "Girar motor". Si lo presiona y mueve el mouse fuera del cuadro de diálogo, puede soltar el clic del mouse y el motor sigue girando.
> 
> @Asizon
> 
> 1. Creo que tienes razón sobre 1100. Porque esto es Dshot y 1100 debería dar alguna velocidad de rotación del motor de todos modos, ¿no?
> 2. No puedo reproducir esto en mis ventanas. ¿Podrías confirmar? Cuando presiono y muevo, el motor sigue girando, pero se detiene tan pronto como lo suelto. Aquí está el código para eso: 
>    `        this._spinButton.on("mouseup **mouseleave**", () => { this._spinButton.removeClass("selected"); this._spinMotor(-1); });`
>    como puede ver, hay "mouseleave" ... ¿Alguna idea? ¡Gracias!

Yes @limonspb it only happens if you release gently and don't move the pointer anymore

2020-11-28 07:57 UTC, Asizon commented
Hover background color for bottons is #ffcc3e @limonspb

2020-11-28 08:02 UTC, limonspb commented
> Hover background color for bottons is #ffcc3e @limonspb , maybe we can add it to all motor tab buttons?

I guess also for Blackbox tab? I think all the rest have a hover effect for buttons.

2020-11-28 09:15 UTC, Asizon commented
Wow!Now looks really awesome, very intuitive navigating between buttons.
Spin button works as expected, i think now is a segure and perfect button.
Spining speed looks better now.
Thankyou for this great feature @limonspb

2020-11-28 09:40 UTC, mikeller commented
Interesting. I made a proposal on how to change the protocol in https://github.com/betaflight/betaflight/pull/10372.

2020-11-28 14:06 UTC, Asizon requested changes
After some test on Android seems that motor spining button doesnt work as expected, with this solution should work.

2020-11-28 14:06 UTC, Asizon commented on src/components/EscDshotDirection/EscDshotDirectionComponent.js
> +        this._spinButton.on("mousedown", () => {
@limonspb We need to add here these atributes for Android compatibility(else it doesnt works) `touchstart` and `touchend` like this:
```
    _setupSpinButtonEvents()
    {
        this._spinButton.on("mousedown touchstart", () => {
            this._spinButton.addClass("selected");
            this._spinMotor(this._selectedMotor);
        });

        this._spinButton.on("mouseup mouseout touchend", () => {
            this._spinButton.removeClass("selected");
            this._spinMotor(-1);
        });
    }
```

2020-11-29 17:04 UTC, limonspb commented
Firmware part is merged into master.
Temporarily sending DSHOT_CMD_TYPE_INLINE commands, not DSHOT_CMD_TYPE_BLOCKING
until blocking commands are fixed in bidirectional dshot.

2020-12-01 07:42 UTC, McGiverGim commented
One suggestion if someone has time to do it: now that we have the "motors" tab with more features, I think we must in a future move all the motors configuration here:
- Move the servos test to the servos tab, to make some room here.
- Move the selection of number of motors, protocol, etc. from others tabs to the motors tab.
In this way I think is most intuitive. All the motor related stuff in the motors tab. Is only a suggestion if someone has time to fight against it. If someone is interested we can discuss it creating a new feature request to let this PR clean.

2020-12-04 02:24 UTC, haslinghuis approved these changes

2020-12-04 02:24 UTC, haslinghuis commented on src/css/tabs/motors.css
> +    height:440px
Found one spacing issue ;-) 
```suggestion
    height: 440px
```

2020-12-04 06:51 UTC, limonspb commented
The main code is ready. I'm just adding some warning messages for when the number of motors in the mixer is 0 or when a non-dshot protocol is selected. So that user knew why he can't use this tool until he fixes the configuration.

2020-12-09 09:22 UTC, haslinghuis requested changes
Great work @limonspb !!! Good quality. Some really minor comments.

2020-12-09 09:22 UTC, haslinghuis commented on src/js/tabs/motors.js
>                  var sum = 0.0;
```suggestion
                let sum = 0.0;
```

2020-12-09 09:22 UTC, haslinghuis commented on src/components/EscDshotDirection/Styles.css
> +	padding-bottom: 9px;
Padding is a little off in this file ;-)  Please use right amount of spaces for identation.

2020-12-09 09:22 UTC, haslinghuis commented on src/components/EscDshotDirection/Styles.css
> +}
Please add newline here.

2020-12-09 17:15 UTC, haslinghuis submitted a review, later dismissed
LGTM!

2020-12-09 17:23 UTC, haslinghuis commented
Accidently approved, status is WIP.

2020-12-11 02:39 UTC, limonspb commented
I think this is ready for review and maybe merged after review is done?

This bug still exists:
https://github.com/betaflight/betaflight/issues/10375
so I had to use dshot inline commands 20 times in a loop to make sure they go through.

I think when the bug is fixed it's easier to replace inline with blocking commands than worry about merge conflicts in the future.

2020-12-11 17:50 UTC, haslinghuis submitted a review, later dismissed
LGTM!

2020-12-13 16:24 UTC, mikeller reviewed
Looks good, some cosmetic remarks.

I think instead of updating the local copy of the openlayers library we should be ditching it and moving to the npm version.

One thing to keep in mind is that not all ESCs supporting Dshot support configuration through Dshot commands - see [Open ESC](https://github.com/AlkaMotors/AM32-MultiRotor-ESC-firmware) for an example.

Re having the wizard / individual methods, it would be nice to collect stats on their usage - but I can add this later in a separate pull request

2020-12-13 16:24 UTC, mikeller commented on src/js/utils/DshotCommand.js
> +    DSHOT_CMD_SIGNAL_LINE_TELEMETRY_DISABLE: 32,
These two can be removed, they are being removed from the firmware as well: https://github.com/betaflight/betaflight/pull/10402

2020-12-14 03:46 UTC, limonspb commented
@mikeller, interesting note about not all ESCs supporting dshot configuration. Shoud I add it into "information notes"?
Like: Note that not all ESC firmwares support configuration through dshot commands. Please check with your ESC firmware.

2020-12-16 13:08 UTC, mikeller commented
@limonspb: Yes, I think a notice like what you propose is appropriate - to tell users that this may not work with their hardware due to factors outside of our control.

2020-12-17 05:26 UTC, limonspb commented
Should be tested with firmware from here until it will be merged into the firmware:
https://github.com/betaflight/betaflight/pull/10406

Sorry, guys, I hope it's a last "big" change in this PR. After switching to blocking Dshot commands I figured they can't be sent too often, right after motors got stopped. So had to implement an "MSP command queue" and some delays in the dialog.

2020-12-18 05:23 UTC, haslinghuis reviewed
I like the MSPCommandQueue idea. Maybe can use it for other things as well.

- What is pushPause() exactly doing? It does send a msp command continuous within a certain interval? If so better rename to pushContinuous() - the interval is evident by the argument.
- PurgeAndStop() is calling stop() but not clear();
- stopAllNow() is calling clear() but not purgeAndStop()

2020-12-18 08:18 UTC, limonspb commented
> I like the MSPCommandQueue idea. Maybe can use it for other things as well.
> 
> * What is pushPause() exactly doing? It does send a msp command continuous within a certain interval? If so better rename to pushContinuous() - the interval is evident by the argument.
> * PurgeAndStop() is calling stop() but not clear();
> * stopAllNow() is calling clear() but not purgeAndStop()

Yeah the naming for these functions can be alittle messed up. Maybe should change them.

pushPause(milliseconds) is inserting a pause into the que. So that if you push more commands after that, they will be executed only after the pause.

PurgeAndStop() keeps the queue going and executing commands, but will kill the "interval timer" when there are no more commands. So maybe it should be "StopWhenEmpty()"?

stopAllNow() is a method in MotorDriver. Maybe it should be named as StopAllMotorsNow()
It clears the queue in case there are any commands left.
and then sends a single command to stop motors. So basically it stops motors almost immediately no matter what.

2020-12-18 12:25 UTC, haslinghuis commented
@limonspb Thanks. Yes renaming will make it more clear to understand the code and abstracts it away (to be adaptable for more than only motor commands).
`pushPause()` --> `pushWithDelay()` or `pushWithInterval()` or `pushAfter()`;
 `StopAllMotors()` would be a better name.
`PurgeAndStop` --> `StopWhenEmpty()` could be called `flushAndCommit()` and should call `clear()` in the end

2020-12-19 19:27 UTC, limonspb commented
Renamed MSPCommandQueue methods according to @haslinghuis  suggestions.
Added Betaflight firmware version check which I previously forgot.

2020-12-19 22:52 UTC, haslinghuis approved these changes
LGTM!

2020-12-22 02:14 UTC, AlkaMotors commented
This will work with open ESC firmware (am32) now too as of version 1.64 so no need of a warning!

2021-01-01 14:30 UTC, mikeller approved these changes

2021-01-01 14:31 UTC, merged