Allows the user to always open the last tab that was used *before* the CLI tab.
betaflight/betaflight-configurator pull request #2302
Opened 2020-12-02 20:10 UTC by spracingofficial

This simply avoids storing 'tab_cli' as the last tab in the first place.

Previously:

* enable 'remember last tab'
* click <some tab that's not setup or cli>
* use tab.
* click 'cli' tab
* `exit`
* reconnect
* observe you're looking at the 'setup' tab.
* expected behaviour is to see the <some tab that's not setup or cli> again.
* click <some tab that's not setup or cli> to get back to where you were before you used the cli.

With this PR:

* enable 'remember last tab'
* click <some tab that's not setup or cli>
* use tab.
* click 'cli' tab
* `exit`
* reconnect
* observe you're looking at the <some tab that's not setup or cli> again.

2020-12-02 20:22 UTC, haslinghuis commented
Interesting. It already worked on Windows but not on Linux. Don't know about OS X.

2020-12-02 20:32 UTC, spracingofficial commented
> Interesting. It already worked on Windows but not on Linux. Don't know about OS X.

Please check the 'Previously' and 'Now' scenarios above, same on all OS, the code isn't OS dependent AFAIK.

2020-12-02 20:34 UTC, haslinghuis requested changes
Two minor coding style issues found. Otherwise approved.

2020-12-02 20:34 UTC, haslinghuis commented on src/js/main.js
> +        const tabName =  $(this).attr("class").split(' ')[0];
```suggestion
        const tabName = $(this).attr("class").split(' ')[0];
```

2020-12-02 20:34 UTC, haslinghuis commented on src/js/main.js
> +                {lastTab: tabName}
```suggestion
                {lastTab: tabName},
```

2020-12-02 20:40 UTC, haslinghuis commented on src/js/main.js
> +                {lastTab: tabName}
Yeah it's better to avoid storing `cli` tab in first place. Totally agree with this change.

2020-12-02 20:40 UTC, haslinghuis commented
Yeah it's better to avoid storing `cli` tab in first place. Totally agree with this change.

2020-12-03 11:09 UTC, spracingofficial commented
Done, commits squashed.

2020-12-03 11:11 UTC, McGiverGim approved these changes
It seems reasonable to me the change.

2020-12-03 13:06 UTC, haslinghuis approved these changes

2021-01-16 10:38 UTC, spracingofficial commented
@McGiverGim / @mikeller Can you re-open this please, it was approved and was only pending due to the Travis build environment being out of Travis credits at the time the PR was created.

2021-01-16 10:48 UTC, mikeller commented
Dear SP Racing Official.
The reason that this pull request has not been merged is that SP Racing is banned from Betaflight for breaches of the community standards.
The reason for this is that a certain D Clifton who at the time used to own SP Racing took it upon himself to publicly denigrate and insult Betaflight and some of Betaflight's core members, and then went on to steal and claim entire releases of Betaflight as 'cleanflight's accomplishments'.
If you would like to be unbanned in Betaflight there are a number of options:
- D Clifton publicly apologises for his denigrations and insults, and the offending cleanflight releases (https://github.com/cleanflight/cleanflight/releases/tag/CLFL_v4.2.0, https://github.com/cleanflight/cleanflight/releases/tag/CLFL_v4.2.2) are deleted;
- you publicly state that D Clifton has been permanently removed from SP Racing.

2021-01-16 10:59 UTC, spracingofficial commented
@mikeller Sure, no problem, in the sake of putting things behind us and moving on your request is granted:

"I, Dominic Clifton of SP Racing, publicaly apologize for any and all denigration and insults of Betaflight and some of it's core members".

I have deleted the requested tags.

Ok, let's move on and get this merged!

Please can you also unban the @hydra account from the BF github repository and slack too?

2021-01-16 11:03 UTC, mikeller commented
Thanks Dominic, apology accepted.

2021-01-16 11:06 UTC, mikeller approved these changes

2021-01-16 11:09 UTC, hydra commented
> Thanks Dominic, apology accepted.
> 
> Done. Let's move forward.

@mikeller Very Gracious, thanks.

I look forward to contributing more significant changes in the future.

2021-01-16 11:15 UTC, merged