Change lexical scope msp
betaflight/betaflight-configurator pull request #2308
Opened 2020-12-08 15:48 UTC by haslinghuis

2020-12-13 17:03 UTC, mikeller requested changes

2020-12-13 17:03 UTC, mikeller commented on src/js/msp/MSPHelper.js
> +            while (true) {
Confusing - please remove.

2020-12-13 17:03 UTC, mikeller commented on src/js/msp/MSPHelper.js
> +        const ledDirectionLetters =        ['n', 'e', 's', 'w', 'u', 'd'];      // in LSB bit order
This is actually repeated from https://github.com/betaflight/betaflight-configurator/pull/2308/files#diff-2a7a24b74c7564918c438782f9a53a977205c0c79fd016a069b6dca546563adfR1202 - should be de-duplicated.

2020-12-13 17:03 UTC, mikeller commented on src/js/msp/MSPHelper.js
> +    for (const index of keys) {
`for ( of )` returns a value and not an index.

2020-12-13 17:03 UTC, mikeller commented on src/js/msp/MSPHelper.js
> +    for (const index of functions) {
`for ( of )` returns a value and not an index.

2020-12-13 19:17 UTC, haslinghuis commented
Thanks. All Fixed as requested per review

2020-12-15 05:13 UTC, haslinghuis commented
Sonar is very confusing about this. Changed back to old style.
![image](https://user-images.githubusercontent.com/8344830/102173859-5eb9fe80-3e9c-11eb-9f3d-87cb309586c1.png)

2020-12-16 13:06 UTC, mikeller requested changes

2020-12-16 13:06 UTC, mikeller commented on src/js/msp/MSPHelper.js
> +    for (const index in functions) {
One more time: It is incorrect to replace `for ( ;; )` with `for ( in )`. Please stop doing this.

2020-12-16 13:43 UTC, mikeller approved these changes

2020-12-16 13:43 UTC, merged