Change lexical scope receiver and failsafe
betaflight/betaflight-configurator pull request #2313
Opened 2020-12-08 17:12 UTC by haslinghuis

2020-12-13 17:37 UTC, mikeller requested changes

2020-12-13 17:37 UTC, mikeller commented on src/js/tabs/failsafe.js
> +            element = $(this);
This really should not set the closure's `element` variable.

2020-12-13 17:37 UTC, mikeller commented on src/js/tabs/receiver.js
> +            const
Weird line break.

2020-12-13 17:37 UTC, mikeller commented on src/js/tabs/receiver.js
> +            const rxPlotE = $('#RX_plot');
A lot of code in configurator uses the `_e` suffix to denote DOM elements - not sure we want to change this.

2020-12-13 21:17 UTC, haslinghuis commented
Thanks. Fixed as requested per review.

2020-12-14 00:21 UTC, mikeller approved these changes

2020-12-14 00:22 UTC, merged