Prevent drag/dop and text selection on most elements.
betaflight/betaflight-configurator pull request #2497
Opened 2021-05-28 15:35 UTC by hydra

I've noticed, over the years, that it was possible to accidentally start a drag-and-drop operation when clicking various elements in the UI, something that shouldn't be possible and certainly isn't possible in native apps.

Similarly, when selecting text it was possible to accidentally select the text of UI elements, again something that shouldn't be possible unless specifically enabled.

This PR:
* disables text selection for everywhere except the CLI and the LOG.
* disables drag/drop for all elements.

2021-05-28 17:38 UTC, McGiverGim requested changes

2021-05-28 17:38 UTC, McGiverGim commented on src/css/main.css
> +* {
Join this with the one of line 25.

2021-05-29 14:06 UTC, hydra commented on src/css/main.css
> +* {
done

2021-05-29 14:13 UTC, hydra commented
@McGiverGim is there a CSS selector that selects *ALL* children, not just direct descendants?  If so I could improve the selectors a bit.

2021-05-31 06:53 UTC, McGiverGim approved these changes

2021-05-31 06:56 UTC, McGiverGim commented
> @McGiverGim is there a CSS selector that selects ALL children, not just direct descendants? If so I could improve the selectors a bit. e.g. `<strong>` and `<span>` elements within the LOG `<p>` elements, and `<br>` elements within the CLI <div>.

@hydra I don' t understand exactly... something like:

```css
tag1 tag2 {
...
}
```
will affect all the tag2 inside a tag1, but it does not need to be a direct descendant.

2021-06-02 20:08 UTC, haslinghuis submitted a review, later dismissed
@Asizon can you confirm, as CSS is your thing :smile:

2021-06-03 18:13 UTC, hydra commented
I need to fix the OSD drag/drop.  Don't merge this yet.  I forgot about that.

2021-06-03 18:28 UTC, hydra commented
@McGiverGim ok, fixed with an additional commit.

2021-06-04 06:52 UTC, McGiverGim approved these changes

2021-06-05 03:21 UTC, haslinghuis approved these changes

2021-06-07 16:37 UTC, Asizon approved these changes

2021-06-09 20:00 UTC, haslinghuis commented
@hydra can you please squash your commits?

2021-06-10 00:45 UTC, blckmn commented
AUTOMERGE: (pass)
 - Github identifies PR as mergeable -> pass
 - PR is not in draft -> pass
 - Assigned to a milestone -> pass
 - cooling off period lapsed (10/06/2021 00:26:17) -> pass
 - commit count less or equal to three (3 commits) -> pass
 - 'Do not merge' label NOT found -> pass
 - 'Needs coordination with betaflight' label NOT found -> pass
 - At least one 'RN:' label found -> pass
 - 'Tested' label found -> pass
 - assigned to an approver (haslinghuis) -> pass
 - approver count at least three (3 approvers) -> pass

2021-06-10 00:48 UTC, blckmn commented
AUTOMERGE: (PASS)
 - Github identifies PR as mergeable -> pass
 - PR is not in draft -> pass
 - Assigned to a milestone -> pass
 - cooling off period lapsed (10/06/2021 00:45:06) -> pass
 - commit count less or equal to three (3 commits) -> pass
 - 'Do not merge' label NOT found -> pass
 - 'Needs coordination with betaflight' label NOT found -> pass
 - At least one 'RN:' label found -> pass
 - 'Tested' label found -> pass
 - assigned to an approver (haslinghuis) -> pass
 - approver count at least three (3 approvers) -> pass

2021-06-10 00:52 UTC, blckmn commented
AUTOMERGE: (PASS)
 - Github identifies PR as mergeable -> pass
 - PR is not in draft -> pass
 - Assigned to a milestone -> pass
 - cooling off period lapsed (10/06/2021 00:48:45) -> pass
 - commit count less or equal to three (3 commits) -> pass
 - 'Do not merge' label NOT found -> pass
 - 'Needs coordination with betaflight' label NOT found -> pass
 - At least one 'RN:' label found -> pass
 - 'Tested' label found -> pass
 - assigned to an approver (haslinghuis) -> pass
 - approver count at least three (3 approvers) -> pass

2021-06-10 01:11 UTC, blckmn commented
AUTOMERGE: (PASS)
 - Github identifies PR as mergeable -> PASS
 - PR is not in draft -> PASS
 - Assigned to a milestone -> PASS
 - cooling off period lapsed (10/06/2021 00:52:14) -> PASS
 - commit count less or equal to three (3 commits) -> PASS
 - 'Don't merge' label NOT found -> PASS
 - 'Needs coordination with betaflight' label NOT found -> PASS
 - At least one 'RN:' label found -> PASS
 - 'Tested' label found -> PASS
 - assigned to an approver (haslinghuis) -> PASS
 - approver count at least three (3 approvers) -> PASS

2021-06-10 01:23 UTC, merged