Fix css height after update NWjs to 0.54
betaflight/betaflight-configurator pull request #2516
Opened 2021-06-20 09:53 UTC by haslinghuis

To go with #2507 to fix dialog height

2021-06-20 10:04 UTC, Asizon requested changes

2021-06-20 10:04 UTC, Asizon commented on src/css/main.css
> +    height: fix-content;
typo :)

2021-06-20 12:26 UTC, haslinghuis commented on src/css/main.css
> +    height: fix-content;
Oops. Fixed. Copy pasta ;-) from here: https://github.com/betaflight/betaflight-configurator/pull/2507#issuecomment-857959106

2021-06-20 12:32 UTC, Asizon approved these changes

2021-06-20 20:25 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - Github identifies PR as mergeable -> FAIL
 - Assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - 'Don't merge' label NOT found -> PASS
 - At least one 'RN:' label found -> PASS
 - 'Tested' label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2021-06-21 07:21 UTC, McGiverGim approved these changes

2021-06-21 20:25 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - Github identifies PR as mergeable -> FAIL
 - Assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - 'Don't merge' label NOT found -> PASS
 - At least one 'RN:' label found -> PASS
 - 'Tested' label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2021-06-25 08:10 UTC, limonspb approved these changes

2021-06-25 20:25 UTC, blckmn commented
AUTOMERGE: (PASS)
 - Github identifies PR as mergeable -> PASS
 - Assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - 'Don't merge' label NOT found -> PASS
 - At least one 'RN:' label found -> PASS
 - 'Tested' label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> PASS

2021-06-25 20:25 UTC, merged