Added latest Rc Smoothing changes
betaflight/betaflight-configurator pull request #2522
Opened 2021-06-28 18:49 UTC by Asizon

This PR goes with part of https://github.com/betaflight/betaflight/pull/10727 and now is 100% coordination finished with this PR changes.
Added Rc smoothing changes maintaining the compatibility and functions of the previous one. I have used some constants but im not sure were they need to go @McGiverGim . I also use text replaces for i18n, but we can think on create new html group and hide the old, what do you think guys?

![image](https://user-images.githubusercontent.com/43983086/123688486-5894d980-d852-11eb-9e9d-7ba8a3491e78.png)

2021-06-28 20:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2021-06-28 21:12 UTC, haslinghuis requested changes

2021-06-28 21:12 UTC, haslinghuis commented on src/js/tabs/receiver.js
> +        let smoothingOnOff = ((semver.gte(FC.CONFIG.apiVersion, API_VERSION_1_44)) ? FC.RX_CONFIG.rcSmoothingMode :
```suggestion
        let smoothingOnOff = semver.gte(FC.CONFIG.apiVersion, API_VERSION_1_44) ? FC.RX_CONFIG.rcSmoothingMode : FC.RX_CONFIG.rcSmoothinType;
```

2021-06-28 21:12 UTC, haslinghuis commented on src/js/tabs/receiver.js
> +        let setPointCutoff = ((semver.gte(FC.CONFIG.apiVersion, API_VERSION_1_44)) ? FC.RX_CONFIG.rcSmoothingSetpointCutoff :
Same as above

2021-06-28 21:12 UTC, haslinghuis commented on src/js/tabs/receiver.js
> +        let feedforwardCutoff = ((semver.gte(FC.CONFIG.apiVersion, API_VERSION_1_44)) ? FC.RX_CONFIG.rcSmoothingFeedforwardCutoff :
Same as above

2021-06-28 21:12 UTC, haslinghuis commented on src/js/tabs/receiver.js
> +        let autoFactor = ((semver.gte(FC.CONFIG.apiVersion, API_VERSION_1_44)) ? FC.RX_CONFIG.rcSmoothingAutoFactor :
Same as above

2021-06-28 21:12 UTC, haslinghuis commented on src/js/tabs/receiver.js
> +            if (setPointCutoff == 0) {
```suggestion
            if (setPointCutoff === 0) {
```

2021-06-28 21:12 UTC, haslinghuis commented on src/js/tabs/receiver.js
> +            if (feedforwardCutoff == 0) {
```suggestion
            if (feedforwardCutoff === 0) {
```

2021-06-28 21:12 UTC, haslinghuis commented on src/js/tabs/receiver.js
> +    let smoothingOnOff = ((semver.gte(FC.CONFIG.apiVersion, API_VERSION_1_44)) ? FC.RX_CONFIG.rcSmoothingMode :
Same as above

2021-06-28 21:12 UTC, haslinghuis commented on src/js/tabs/receiver.js
> +        if (feedforwardCutoff == 0 || setPointCutoff == 0) {
```suggestion
        if (feedforwardCutoff === 0 || setPointCutoff === 0) {
```

2021-06-28 21:12 UTC, haslinghuis commented on src/js/tabs/receiver.js
> +    if (smoothingOnOff == 0) {
```suggestion
    if (smoothingOnOff === 0) {
```

2021-06-28 21:12 UTC, haslinghuis commented on src/js/tabs/receiver.js
> +    if (feedforwardCutoff == 0) {
```suggestion
    if (feedforwardCutoff === 0) {
```

2021-06-28 21:12 UTC, haslinghuis commented on src/js/tabs/receiver.js
> +    if (setPointCutoff == 0) {
```suggestion
    if (setPointCutoff === 0) {
```

2021-06-28 21:12 UTC, haslinghuis commented on src/js/tabs/receiver.js
> +    let setPointCutoff = ((semver.gte(FC.CONFIG.apiVersion, API_VERSION_1_44)) ? FC.RX_CONFIG.rcSmoothingSetpointCutoff :
same as above

2021-06-28 21:12 UTC, haslinghuis commented on src/js/tabs/receiver.js
> +    let feedforwardCutoff = ((semver.gte(FC.CONFIG.apiVersion, API_VERSION_1_44)) ? FC.RX_CONFIG.rcSmoothingFeedforwardCutoff :
same as above

2021-06-28 21:12 UTC, haslinghuis commented on src/js/tabs/receiver.js
> +    let autoFactor = ((semver.gte(FC.CONFIG.apiVersion, API_VERSION_1_44)) ? FC.RX_CONFIG.rcSmoothingAutoFactor :
```suggestion
    let autoFactor = semver.gte(FC.CONFIG.apiVersion, API_VERSION_1_44) ? FC.RX_CONFIG.rcSmoothingAutoFactor : FX.RX_CONFIG.rcSmoothingAutoSmoothness;
```

2021-06-28 21:27 UTC, haslinghuis commented
Please also solve the sonar complaints, that's why the Windows build is failing...

2021-06-29 07:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2021-06-29 19:16 UTC, haslinghuis submitted a review, later dismissed

2021-06-29 20:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2021-07-01 13:53 UTC, McGiverGim commented
I prefer always to have all the elements in the HTML and hide the elements that don't need to be here. It seems to me that needs less maintenance that to have a text totally dynamic.
For the rest, it seems good to me.

2021-07-02 10:43 UTC, McGiverGim commented on src/js/tabs/receiver.js
> +        $('.rcSmoothingOn').text('ON');
Esto debe ir al i18n?

2021-07-06 06:33 UTC, Asizon commented
After some talks with @McGiverGim I have reanmed old wrong named features, also removed unneeded MSP changes. Basically 80% of the PR are a renames.

2021-07-06 13:26 UTC, haslinghuis commented on src/js/tabs/receiver.js
> +        $('.rcSmoothingOn').text('ON');
ON and OFF should be translated.

2021-07-07 11:35 UTC, haslinghuis approved these changes

2021-07-07 13:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2021-07-21 09:36 UTC, McGiverGim approved these changes

2021-07-31 23:59 UTC, limonspb approved these changes

2021-08-01 04:17 UTC, blckmn commented
AUTOMERGE: (PASS)
 - github identifies PR as mergeable -> PASS
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> PASS

2021-08-01 04:17 UTC, merged