Add OSD_TOTAL_PACK (with betaflight/pull/10808)
betaflight/betaflight-configurator pull request #2532
Opened 2021-07-09 07:49 UTC by bree29

### Add OSD_TOTAL_PACK

Satisfies `Needs coordination with betaflight-configurator` label on the [original PR](https://github.com/betaflight/betaflight/pull/10808).

I tested the betaflight-configurator on Linux64 platform, and with modified Betaflight 4.3 (the one in PR) on STM32F7X2 target
```
# config: manufacturer_id: AIKO, board_name: AIKONF7, version: 34f72565, date: 2019-10-03T17:08:47Z
```

All settings went good on BF configurator and seems OK.

I'll test the feature itself this weekend ; all is looking good on the betaflight-configurator side.

2021-07-09 08:34 UTC, Asizon requested changes

2021-07-09 08:34 UTC, Asizon commented on src/js/tabs/osd.js
> +                F.STAT_TOTAL_PACKS,
It should be added to API_VERSION_1_44, the existing code seems wrong, @limonspb why you added Flight count in 1.42?

2021-07-09 08:46 UTC, Asizon requested changes

2021-07-09 08:46 UTC, Asizon commented on src/js/tabs/osd.js
> +                                                        F.TOTAL_PACKS,
Why here is TOTAL_PACKS and not STAT_TOTAL_PACKS?

2021-07-09 08:46 UTC, Asizon commented on src/js/tabs/osd.js
> +                                                        F.TOTAL_PACKS,
Also this bit should go the last one on the list.

2021-07-09 11:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2021-07-10 08:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2021-07-12 19:43 UTC, bree29 commented
```
yarn
yarn test
yarn start
```

Feature tested on BF side (see original PR)

Reviews required by @Asizon have been made.

2021-07-13 22:03 UTC, haslinghuis submitted a review, later dismissed

2021-07-14 07:06 UTC, Asizon approved these changes

2021-08-01 00:01 UTC, limonspb commented on locales/en/messages.json
> +        "message": "Total number of used packs"
flown packs could be better? Need a native English speaker here :)

2021-08-05 14:03 UTC, bree29 commented
Accidently closed the PR alongside my rebase. Everything should work great right now. Please let me now.

2021-08-13 22:39 UTC, haslinghuis submitted a review, later dismissed

2021-08-22 07:47 UTC, Asizon approved these changes
LGTM!

2021-08-22 09:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2021-08-30 01:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> FAIL
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2021-08-31 01:53 UTC, ctzsnooze submitted a review, later dismissed

2021-08-31 02:13 UTC, haslinghuis commented
@bree29 please squash your commits. Attached `Don't merge` label awaiting merging of firmware part.

2021-08-31 03:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> PASS
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> FAIL
 - `Don't merge` label NOT found -> FAIL
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2021-08-31 05:28 UTC, mikeller approved these changes

2021-08-31 08:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> PASS
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> FAIL
 - `Don't merge` label NOT found -> FAIL
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> PASS

2021-12-04 00:05 UTC, ctzsnooze commented
@bree29 - If you want this merged into 10.8, please squash your commits and indicate that you still think it is important.

Otherwise we will tag it for 10.9 and think about it after 4.3 / 10.8 are released.

2022-01-10 22:05 UTC, bree29 commented
> @bree29 - If you want this merged into 10.8, please squash your commits and indicate that you still think it is important.
> 
> Otherwise we will tag it for 10.9 and think about it after 4.3 / 10.8 are released.

Just in case my updates from upstream will be an issue (the "one commit" thing, that were 5 here), just as it was in the betaflight part, I followed the same solution to update it to HEAD & squash my commit. Since I must do something wrong in my rebase sequences.

Sorry for the inconvenience of having to re-approving it for merging.

2022-01-10 22:45 UTC, haslinghuis commented
Merging upstream changes does count as commit but is actually not when rebasing. Found out after using letting vscode to do this for me. So I'm back on the command line.

2022-01-11 00:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> FAIL
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2022-01-11 02:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2022-01-11 05:06 UTC, Asizon commented
Firmware pr is labeled for 4.4,i think we are not in time to merge this new feature into 4.3

2022-06-18 06:21 UTC, limonspb approved these changes

2022-06-18 22:10 UTC, bree29 commented
@limonspb , do I need to rebase before reviews are approved ? Same question for the firmware PR

2022-06-18 22:25 UTC, haslinghuis approved these changes

2022-06-18 22:25 UTC, haslinghuis commented
@bree29 there are no conflicts. Both PR's are ready to merge. Thanks!

2022-10-15 19:21 UTC, closed without merging