Update rx config note
betaflight/betaflight-configurator pull request #2635
Opened 2021-10-15 03:15 UTC by ctzsnooze

Re-opening PR #2562 with some minor text modifications.

This provides more comprehensive help than the previous tooltip.

2021-10-16 03:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2021-10-16 19:28 UTC, haslinghuis commented
@ctzsnooze this needs a rebase

2021-11-25 02:04 UTC, limonspb approved these changes, later dismissed

2021-11-25 06:45 UTC, Asizon requested changes

2021-11-25 06:45 UTC, Asizon commented on locales/en/messages.json
> +        "message": "<b>Basic setup</b>: For serial connections, go to the Ports tab and enable ‘Serial Rx’ for the correct UART.  In the Receivers tab, choose ‘Serial based receiver…’, and set the co
disable adc filter url is wrong, should be https://github.com/betaflight/betaflight/blob/master/docs/Rx.md#disabling-the-opentxedgetx-adc-filter

2021-11-27 07:07 UTC, Asizon approved these changes, later dismissed

2021-11-27 07:14 UTC, limonspb submitted a review, later dismissed

2021-11-27 13:09 UTC, haslinghuis approved these changes, later dismissed

2021-11-27 13:14 UTC, haslinghuis approved these changes

2021-11-27 14:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> FAIL
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2021-11-27 15:07 UTC, haslinghuis requested changes
Tried to bring master in, but that didn't solve it. Please rebase manual

2021-11-27 16:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> FAIL
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2021-11-28 01:57 UTC, ctzsnooze commented
Fixed the link syntax, but closing in favour of #2671 which is intended to give a clean face for the receiver tab for 4.3

2021-11-28 01:57 UTC, closed without merging