Fix integrated yaw usage
betaflight/betaflight-configurator pull request #2651
Opened 2021-11-07 09:25 UTC by Asizon

Allow manual pid change when integrated yaw is enabled.

2021-11-07 11:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2021-11-08 02:32 UTC, haslinghuis submitted a review, later dismissed

2021-11-08 04:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2021-11-08 10:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2021-11-08 13:51 UTC, haslinghuis commented
After testing I found we have to press the Enable button twice.

Moving the code to pid_tuning.js solves it:

```
        $('input[id="useIntegratedYaw"]').change(function() {
            const checked = $(this).is(':checked');
            if (semver.gte(FC.CONFIG.apiVersion, API_VERSION_1_44)) {
                this.sliderPidsMode = 0;
                $('#pid_main .pid_data input').prop('disabled', false);
            }
            $('#pidTuningIntegratedYawCaution').toggle(checked);
        }).change();

```

2021-11-25 02:03 UTC, limonspb approved these changes

2021-11-25 12:33 UTC, limonspb approved these changes

2021-11-25 12:36 UTC, haslinghuis approved these changes

2021-11-30 00:48 UTC, ctzsnooze commented
In my testing, the PR allows me to edit manually edit PID values, when integrated yaw is enabled, but if I save the Profile, then my changes are lost and I cannot edit the values anymore.

2021-11-30 04:17 UTC, haslinghuis commented
@ctzsnooze Can't reproduce as I've tested

2021-11-30 07:00 UTC, Asizon commented
Yes, we need to take a look into this issue. Ithink sliders are not changing correctly from RPY to off.

2021-11-30 13:28 UTC, haslinghuis requested changes

2021-11-30 13:28 UTC, haslinghuis commented on src/js/tabs/pid_tuning.js
> +                this.sliderPidsMode = 0;
```suggestion
                TuningSliders.sliderPidsMode = 0;
```

2021-11-30 20:12 UTC, haslinghuis commented
Sorry @Asizon I made a typo in my first suggestion. Now I have more time I had a fresh look and found you should move the fix to around line 1936 as this only applies to sliders. We can leave the code around 550 untouched:
```
$('input[id="useIntegratedYaw"]').change(() => {
    if (semver.gte(FC.CONFIG.apiVersion, API_VERSION_1_44)) {
        TuningSliders.sliderPidsMode = 0;
    }
    TuningSliders.updatePidSlidersDisplay();
}
```

The typo was `this.sliderPidsMode` instead of `TuningSliders.sliderPidsMode`.

2021-11-30 21:19 UTC, klutvott123 commented
So enabling integrated yaw should disable sliders for RPY, not just Y?

2021-11-30 21:26 UTC, haslinghuis commented
Hmm you suggest setting slider to RP mode instead to OFF? Makes sense to me. Testing now.

2021-11-30 22:15 UTC, klutvott123 commented
I suggest setting it to RP IF it's currently set to RPY

2021-12-01 00:39 UTC, haslinghuis commented
@Asizon 

Worked out the changes needed @klutvott123 suggested:

[diff2.txt](https://github.com/betaflight/betaflight-configurator/files/7629756/diff2.txt)

2021-12-04 00:10 UTC, ctzsnooze commented
@Asizon - do you have time to update this PR and test it?  We need to resolve this for 10.8 RC1 as soon as possible.

2021-12-08 13:31 UTC, haslinghuis approved these changes

2021-12-09 23:31 UTC, ctzsnooze approved these changes

2021-12-09 23:31 UTC, ctzsnooze commented
Tested, works very effectively.

2021-12-10 05:49 UTC, limonspb approved these changes

2021-12-10 05:50 UTC, merged