Added Betaflight Discord server link to the landing page
betaflight/betaflight-configurator pull request #2704
Opened 2021-12-22 05:43 UTC by limonspb

it's probably time :)

![image](https://user-images.githubusercontent.com/2925027/147041742-d333577d-c047-407e-a491-098b957141eb.png)

2021-12-22 07:46 UTC, haslinghuis requested changes

2021-12-22 07:46 UTC, haslinghuis commented on locales/en/messages.json
> +    "defaultDiscodText": {
```suggestion
    "defaultDiscordText": {
```

2021-12-22 07:46 UTC, haslinghuis commented on src/tabs/landing.html
> +                    <div class="socialMediaText" i18n="defaultDiscodText"></div>
```suggestion
                    <div class="socialMediaText" i18n="defaultDiscordText"></div>
```

2021-12-22 08:18 UTC, limonspb commented on src/tabs/landing.html
> +                    <div class="socialMediaText" i18n="defaultDiscodText"></div>
lol

2021-12-22 08:20 UTC, haslinghuis approved these changes

2021-12-22 13:01 UTC, McGiverGim commented
The decision is to move to discord?

If that is true, we must "lock" the old slack chat with a message to move to the new place. Having two places where the users can go to find support I think is not a good idea.

So my opinion is first move to the new place, later add the info in the Configurator.

2021-12-22 16:33 UTC, DusKing1 commented
Didn't we just vote on moving topic before? Most of us don't want move to discord.

2021-12-22 18:03 UTC, limonspb commented
> The decision is to move to discord?
> 
> If that is true, we must "lock" the old slack chat with a message to move to the new place. Having two places where the users can go to find support I think is not a good idea.
> 
> So my opinion is first move to the new place, later add the info in the Configurator.

Not moving from slack. Just adding discord. And if it goes good, later we can discuss about removing slack if we need to.

And we already have multiple places where users can find help. Adding one more with infinite history, better popularity isn't anything bad, is it?

2021-12-23 12:50 UTC, chmelevskij commented on src/css/tabs/landing.css
> +.text1, .text2, .text3{
```suggestion
.text1, .text2, .text3 {
```

2021-12-23 23:34 UTC, limonspb commented on src/css/tabs/landing.css
> +.text1, .text2, .text3{
my bad =)

2021-12-23 23:37 UTC, haslinghuis commented
Slack is for the community. Discord is developers only at the moment making zoom like calls possible.

2021-12-24 00:08 UTC, Zuldan commented
![Chat systems](https://user-images.githubusercontent.com/12680150/147300774-a67336f1-aedc-4a0d-933b-ede9ee1974e3.PNG)
 
Once Betaflight has migrated over to Discord, I can finally uninstall Slack.

2021-12-26 06:51 UTC, ctzsnooze commented
I don't mind having multiple places to communicate, and some people prefer Discord, so I don't mind both.

I would value a private developer area on Discord for the video conferencing it provides.

2022-01-03 10:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2022-01-03 12:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2022-01-06 23:43 UTC, ctzsnooze approved these changes

2022-01-07 00:15 UTC, haslinghuis approved these changes

2022-01-07 00:33 UTC, blckmn approved these changes

2022-01-07 00:33 UTC, merged