Discord link fix: make permanent (never expire)
betaflight/betaflight-configurator pull request #2751
Opened 2022-01-12 10:27 UTC by limonspb

Forgot that by default discord invite link is being expired after 7 days.
Changing the link to a permanent one.

2022-01-12 11:09 UTC, blckmn requested changes
You can use

HTTPS://discord.betaflight.com/invite

2022-01-12 12:34 UTC, KarateBrot approved these changes

2022-01-12 13:33 UTC, haslinghuis approved these changes

2022-01-12 15:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2022-01-12 21:42 UTC, blckmn approved these changes

2022-01-13 00:19 UTC, ctzsnooze approved these changes

2022-01-13 00:30 UTC, merged