Test throttle selector UI component
betaflight/betaflight-configurator pull request #2766
Opened 2022-01-20 09:45 UTC by atomgomba

This is a UI component for selecting throttle value in the motor setup dialogs. Currently it is not functional in the sense that throttle value changes do not take effect because actual motor control is better understood by @limonspb so take this as half-baked strictly UI feature to free limon from the hassle of dealing with HTML/CSS.

![Screenshot from 2022-01-20 10-22-10](https://user-images.githubusercontent.com/33358/150313903-d96d69bc-e335-4c6d-8da4-2cb549be0c42.png)

![Screenshot from 2022-01-20 10-21-43](https://user-images.githubusercontent.com/33358/150313926-0c290b21-fcfe-405a-a806-a5ee8bd5f17d.png)

2022-01-20 11:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2022-01-21 05:39 UTC, limonspb commented
@atomgomba 
plus check a couple of sonar warnings plz here
![image](https://user-images.githubusercontent.com/2925027/150472277-7c4425af-0c41-4da0-8cc1-72bc46848eba.png)

2022-01-21 06:32 UTC, Asizon commented
This PR seems a needed fix to make the new motor order dialog working properly since latest changes on how idle works on firmware. So i have asigned to 10.8.0 milestone.

2022-01-21 06:38 UTC, Asizon requested changes
Windows enviroment builds are failing here:

```
D:\a\1\s\src\components\shared\TestThrottleSelector\TestThrottleSelectorComponent.js
  4:26  error  Parsing error: Unexpected token =
```

2022-01-21 07:26 UTC, limonspb commented
> Windows enviroment builds are failing here:
> 
> ```
> D:\a\1\s\src\components\shared\TestThrottleSelector\TestThrottleSelectorComponent.js
>   4:26  error  Parsing error: Unexpected token =
> ```

yeah i think our Chrome version is not supporting static fields yet.

2022-01-21 09:16 UTC, atomgomba commented
It's a pitty but it seems like if the supported EVMA version is different in the test env than the app? 😳

2022-01-21 09:44 UTC, limonspb commented
> It's a pitty but it seems like if the supported ECMA version is different in the test env than the app? 😳

When I started working on presets I also wanted to use static class variables. But after some compatibility researsh I found I'd better not to yet. I don't remember why tho :)

2022-01-21 11:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2022-01-23 13:24 UTC, haslinghuis commented
See: https://chromestatus.com/feature/6482797915013120

We are using:
```
navigator.appVersion.match(/.*Chrome\/([0-9\.]+)/)[1];
"91.0.4472.114"
```

According to NW.js we should be on Node 16.4.0 already:
```
        {
            "version": "v0.54.1",
            "date": "2021/07/02",
            "files": ["win-x64", "win-ia32", "linux-x64", "linux-ia32", "osx-x64"],
            "flavors": ["normal", "sdk"],
            "components": {
                "node": "16.4.0",
                "chromium": "91.0.4472.114"
            }
        },
```

2022-01-23 23:39 UTC, haslinghuis commented on src/components/shared/TestThrottleSelector/TestThrottleSelectorComponent.js
> +                    const btn = $(itemTpl.replace("{{ label }}", opt + "%"))
```suggestion
                    const btn = $(itemTpl.replace("{{ label }}", `${opt}%`))
```

2022-01-24 08:22 UTC, limonspb approved these changes

2022-02-12 03:57 UTC, blckmn submitted a review, later dismissed

2022-02-13 19:18 UTC, atomgomba commented
I cannot merge for some reason

2022-02-14 05:04 UTC, limonspb commented
> I cannot merge for some reason

what do you mean?

2022-09-17 23:02 UTC, blckmn approved these changes

2022-09-21 21:46 UTC, haslinghuis approved these changes

2022-10-20 01:27 UTC, closed without merging