update to node 16
betaflight/betaflight-configurator pull request #2782
Opened 2022-01-29 08:21 UTC by chmelevskij

Update to node 16

2022-01-29 08:50 UTC, Asizon approved these changes
Cool!!

2022-01-29 10:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2022-01-29 11:42 UTC, haslinghuis approved these changes

2022-01-30 09:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2022-02-04 23:47 UTC, ctzsnooze commented
Should this be for 10.8?
We should keep node version the same across Configurator and Log Viewer, and not change late in the dev process unless it is to fix a bug.

2022-02-04 23:49 UTC, haslinghuis commented
According to @Asizon it's just a build improvement, already provided a PR for Blackbox to synchronize.

2022-05-07 23:09 UTC, haslinghuis requested changes
Please update to v16.15.0 in remaining files.

2022-05-07 23:09 UTC, haslinghuis commented on .nvmrc
> +v16.13.2
```suggestion
v16.15.0
```

2022-05-07 23:09 UTC, haslinghuis commented on .travis.yml
> +  - 16.13.2
```suggestion
  - 16.15.0
```

2022-05-19 21:16 UTC, haslinghuis commented
Superseded by https://github.com/betaflight/betaflight-configurator/pull/2913

2022-05-19 21:16 UTC, closed without merging