Presets: fix for multiple select dropdowns with 199+ elements
betaflight/betaflight-configurator pull request #2790
Opened 2022-02-02 08:34 UTC by limonspb

The number of keywords reached 199 and revealed a bug in multiple select preventing it from scrolling.

Fixes:
https://github.com/betaflight/betaflight-configurator/issues/2789

the issue caused by the bug in multiple select jquery component. Described here:
https://github.com/wenzhixin/multiple-select/issues/552

2022-02-02 10:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2022-02-02 10:42 UTC, chmelevskij approved these changes
😄 @limonspb we need to just rewrite this thing with vue finally and then write tests for this upfront 😉

2022-02-02 11:22 UTC, Asizon requested changes
I dont think that we need a timer here, we can made a better workarround thought.

2022-02-02 15:01 UTC, limonspb commented
> 😄 @limonspb we need to just rewrite this thing with vue finally and then write tests for this upfront 😉

Because vue third party components can't have bugs? Lol

2022-02-02 15:08 UTC, haslinghuis commented
@limonspb there is a better workaround in the attached link.
```
$(function() {
   $('select').multipleSelect();
  
   // here I'm revealing the container that has the dropdowns
   // and after it's done showing, I refresh the multipleSelect
   $('#btn').click(() => $('#wrapper').show(function() {
      $('select').multipleSelect('refresh');	
   }));
})
```

2022-02-02 15:10 UTC, limonspb commented
> @limonspb there is a better workaround in the attached link.
> 
> ```
> $(function() {
>    $('select').multipleSelect();
>   
>    // here I'm revealing the container that has the dropdowns
>    // and after it's done showing, I refresh the multipleSelect
>    $('#btn').click(() => $('#wrapper').show(function() {
>       $('select').multipleSelect('refresh');	
>    }));
> })
> ```

This is basically the same solution. They are using animation of toggle like setTimout(). Which is probably even a little more confusing

2022-02-02 15:17 UTC, haslinghuis commented
You could add a comment for maintenance and clarity:  `// TODO: Remove workaround if fixed in wenzhixin/multiple-select#552`

2022-02-02 15:24 UTC, haslinghuis commented
Point is we should avoid using a timeout like @Asizon said.

2022-02-02 17:47 UTC, limonspb commented
> Point is we should avoid using a timeout like @Asizon said.

That does not mean we should hide timeout behind the fake animations

2022-02-03 09:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2022-02-04 23:46 UTC, ctzsnooze commented
When you guys agree, we can move ahead ;-)

2022-02-05 09:19 UTC, Asizon commented
@ctzsnooze there is nothing to agree, we are looking for a better solution :)

2022-02-06 09:58 UTC, Asizon approved these changes

2022-02-06 12:53 UTC, haslinghuis approved these changes

2022-02-06 12:53 UTC, merged