Show firmware loaded in firmware flasher tab
betaflight/betaflight-configurator pull request #2834
Opened 2022-02-26 13:45 UTC by haslinghuis

![image](https://user-images.githubusercontent.com/8344830/155844917-564bc39c-e79b-4bc0-b39b-618791e5188a.png)

2022-02-26 14:56 UTC, McGiverGim requested changes
Good idea!! Only one suggestion...

2022-02-26 14:56 UTC, McGiverGim commented on locales/en/messages.json
> +        "message": "Loaded Local Firmware: $1 ($2 bytes)"
Now that you are changing it, better to use the ”object" way with {{firmwareSelected}} and {{size}} for example. I think is better for understanding the code and helps translators.

2022-02-26 16:21 UTC, haslinghuis commented
One problem to solve: throwing away the config when loading online target without choosing a new one.

2022-02-26 17:10 UTC, McGiverGim approved these changes

2022-02-26 18:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2022-02-26 20:08 UTC, daleckystepan commented
Tested on MacOS, works fine.

2022-02-27 00:20 UTC, ctzsnooze approved these changes

2022-02-27 00:27 UTC, limonspb approved these changes

2022-02-27 00:30 UTC, merged