Fixing a sporadic timing error prevents a backup from being written correctly to a file
betaflight/betaflight-configurator pull request #2876
Opened 2022-03-29 17:58 UTC by mrRobot62

On mac I found a sporadic timing error which prevents to write a complete backup into a file. It must be something with the connection between FC and BF configurator, if there is a delay there, the case occurs

Problem was found here
`       GUI.interval_add(readingDumpIntervalName, () => {
            const currentTime = performance.now();
            if (currentTime - lastCliStringReceived > 500) {
                this.cliEngine.unsubscribeOnRowCame();
                GUI.interval_remove(readingDumpIntervalName);
                resolve(diffAll);
            }
`
Unfortunately increasing 500 to a bigger number do not fix this issue.
Sometimes it returns more or less nothing.

Based on a sporadic error my fix is not high spophisticated. In function `TABS.presets.onSaveConfigClick` I check text length, if it is to small, quit function with a warning otherwise write file.

Change `diff all` to `dump all` based on function name which is called.

## Important considerations when opening a pull request:

1. Make sure you do not make the changes you want to open a pull request for on the `master` branch of your fork, or open the pull request from the `master` branch of your fork. Some of our integrations will fail if you do this, resulting in your pull request not being accepted. If this is your first pull request, it is probably a good idea to first read up on how opening pull requests work (https://opensource.com/article/19/7/create-pull-request-github is a good introduction);

2. Pull requests will only be accepted if they are opened against the `master` branch of our repository. Pull requests opened against other branches without prior consent from the maintainers will be closed;

3. Please follow the coding style guidelines: https://github.com/betaflight/betaflight/blob/master/docs/development/CodingStyle.md

4. Keep your pull requests as small and concise as possible. One pull request should only ever add / update one feature. If the change that you are proposing has a wider scope, consider splitting it over multiple pull requests. In particular, pull requests that combine changes to features and one or more new targets are not acceptable.

5. Ideally, a pull request should contain only one commit, with a descriptive message. If your changes use more than one commit, rebase / squash them into one commit before submitting a pull request. If you need to amend your pull request, make sure that the additional commit has a descriptive message, or - even better - use `git commit --amend` to amend your original commit.

6. All pull requests are reviewed. Be ready to receive constructive criticism, and to learn and improve your coding style. Also, be ready to clarify anything that isn't already sufficiently explained in the code and text of the pull request, and to defend your ideas.

7. We use continuous integration (CI) with [Travis](https://travis-ci.com/betaflight) to build all targets and run the test suite for every pull request. Pull requests that fail any of the builds or fail tests will most likely not be reviewed before they are fixed to build successfully and pass the tests. In order to get a quick idea if there are things that need fixing **before** opening a pull request or pushing an update into an existing pull request, run `make pre-push` to run a representative

2022-03-29 20:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2022-03-30 18:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> PASS
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2022-04-01 22:12 UTC, haslinghuis commented
@mrRobot62 please see also: https://github.com/betaflight/betaflight-configurator/pull/2879

2022-04-13 02:28 UTC, limonspb commented
@mrRobot62 could you please test the latest master and check if we need this fix from you now. Thanks!

2022-04-13 02:30 UTC, limonspb requested changes
@mrRobot62 could you please test the latest master and check if we need this fix from you now. Thanks!

2022-04-13 02:30 UTC, limonspb commented on src/tabs/presets/presets.js
> +    this.cliEngine.sendLine(CliEngine.s_commandDumpAll);
this should stay Diff not dump. The idea is to actually save diff as it's smaller, faster to save/load and more flexible.

2022-05-21 04:38 UTC, closed without merging