Fix MSP_BOARD_INFO accumulation
betaflight/betaflight-configurator pull request #2937
Opened 2022-05-29 00:39 UTC by haslinghuis

Fixes PR FC.CONFIG.boardName parameter accumulating previous values.

2022-05-29 03:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2022-05-29 14:41 UTC, haslinghuis commented
Looks like we also have a quota issue.
```
    quota: function() {
        let data = '';
        for(const key in window.localStorage){
            if (window.localStorage.hasOwnProperty(key)) {
                data += window.localStorage[key];
            }
        }

        return data ? 3 + ((data.length * 16) / (8 * 1024)) : 0;
    },
```

2022-05-29 22:40 UTC, limonspb requested changes

2022-05-29 22:40 UTC, limonspb commented on src/js/SessionStorage.js
> +                    console.log(e);
console.error maybe?

2022-05-29 22:40 UTC, limonspb commented on src/js/SessionStorage.js
> +                    console.log(e);
console.error?

2022-05-29 22:40 UTC, limonspb commented on src/js/SessionStorage.js
> +                console.log(e);
console.error

2022-05-29 22:47 UTC, haslinghuis commented on src/js/SessionStorage.js
> +                    console.log(e);
Fixed

2022-05-29 22:47 UTC, haslinghuis commented on src/js/SessionStorage.js
> +                    console.log(e);
Fixed

2022-05-29 22:48 UTC, haslinghuis commented on src/js/SessionStorage.js
> +                console.log(e);
Fixed

2022-05-30 04:48 UTC, limonspb approved these changes

2022-05-30 06:11 UTC, McGiverGim commented
What happens with old values stored in the local storage? They will remain there until the user deletes the folder in the computer?

2022-05-30 08:57 UTC, chmelevskij submitted a review, later dismissed

2022-05-30 11:02 UTC, haslinghuis commented
Old values will remain until user removes the folder.

2022-05-31 02:01 UTC, limonspb approved these changes

2022-05-31 10:46 UTC, McGiverGim approved these changes
The cleanup is very simple, maybe we need to store some "version" in the localStorage, and act according to the change of version. But for the moment, I think is enough with your code. I suppose this is a exceptional situation and we can remove the cleaning in one or two versions.

2022-05-31 11:34 UTC, Asizon approved these changes

2022-05-31 11:35 UTC, merged