vtx_osd_variant_fix
betaflight/betaflight-configurator pull request #2964
Opened 2022-06-28 19:49 UTC by P-I-Engineer

this is a PR to replace https://github.com/betaflight/betaflight-configurator/pull/2755 i had too many github issues to salvage

I've created an osd variant for VTX channel that displays only the VTXpower.

pull request is partial approved in betaflight here
https://github.com/betaflight/betaflight/pull/11275

![image](https://user-images.githubusercontent.com/11393479/176271425-aa719c00-2df1-4f4b-ab82-df840a7c3550.png)
![image](https://user-images.githubusercontent.com/11393479/176271460-d3d9388c-ae35-4df8-b582-4e6d17dac204.png)
![image](https://user-images.githubusercontent.com/11393479/176271487-7c80a1bd-ad71-4963-ad03-ca64a88e70c4.png)

2022-06-28 20:43 UTC, haslinghuis commented on src/js/tabs/osd.js
> +                ],
Please fix indentation.
```suggestion
           ],
```

2022-06-28 20:44 UTC, haslinghuis requested changes

2022-06-28 20:44 UTC, haslinghuis commented on src/js/tabs/osd.js
> +            }
Missing comma:
```suggestion
            },
```

2022-06-28 22:18 UTC, P-I-Engineer commented
i know this is messed up again, i'm having a heck of a time with squashing commits

2022-06-28 22:30 UTC, haslinghuis approved these changes

2022-06-28 22:32 UTC, haslinghuis commented
@P-I-Engineer please check https://github.com/betaflight/betaflight/wiki/Betaflight-Contribution. You need to master this.

2022-06-28 22:35 UTC, P-I-Engineer commented
i keep getting merge commits and not sure where they're coming from

2022-06-28 23:32 UTC, P-I-Engineer commented
got it

2022-06-29 00:41 UTC, haslinghuis approved these changes

2022-06-29 02:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2022-09-17 23:09 UTC, blckmn approved these changes

2022-09-17 23:09 UTC, merged