Change dynamic Notch MinHz Default
betaflight/betaflight-configurator pull request #3020
Opened 2022-09-08 20:04 UTC by haslinghuis

Fixes: https://github.com/betaflight/betaflight/pull/11827

2022-09-08 21:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2022-09-09 05:08 UTC, Asizon requested changes

2022-09-09 05:08 UTC, Asizon commented on src/js/fc.js
> +            if (semver.gte(this.CONFIG.apiVersion, API_VERSION_1_45)) {
Firmwsre side is taged for 4.3

2022-09-09 20:35 UTC, Asizon approved these changes

2022-09-15 15:03 UTC, McGiverGim approved these changes

2022-09-17 23:06 UTC, blckmn approved these changes

2022-09-17 23:07 UTC, merged