Fix permissions in debian package
betaflight/betaflight-configurator pull request #3028
Opened 2022-09-28 16:55 UTC by haslinghuis

Fixes: #3009

2022-09-28 17:08 UTC, howels requested changes

2022-09-28 17:08 UTC, howels commented on gulpfile.js
> +                `chmod -R +xr /opt/betaflight/betaflight-configurator/`,
This `chmod -R +xr` will make all files in the directory executable, whereas we only want the two binaries, `/opt/betaflight/betaflight-configurator/chrome_crashpad_handler` and `/opt/betaflight/betaflight-configurator/betaflight-configurator` to be executable - not bitmaps, libraries etc.
So the three commands are needed, then the capital X in `chmod -R +Xr /opt/betaflight/betaflight-configurator/` sets the *directory only* to be executable which means that the user can read which files are inside the directory.

2022-09-28 17:21 UTC, howels requested changes
After reading the rest of gulpfile.js I think we should use $`{LINUX_INSTALL_DIR}/${metadata.name}` in place of `/opt/betaflight/betaflight-configurator` because this path can change depending on OS preferences. Sorry to ask again.

2022-09-28 17:58 UTC, howels approved these changes
Tested and working perfectly now, appreciate the fix.

2022-09-28 19:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2022-09-29 05:02 UTC, ctzsnooze approved these changes

2022-09-29 11:33 UTC, McGiverGim approved these changes
LGTM. Strange that this permission problem does not happen on all systems. For a future, if this continue growing, maybe is better to move the scripts to a external file. In this way we can do more complicated things.

2022-09-30 13:28 UTC, nerdCopter commented
> [Betaflight-Configurator-Linux](https://github.com/betaflight/betaflight-configurator/suites/8517889752/artifacts/379554352) 

`10.9.0-debug-3d88148`: 

* Ubuntu 20.04.5 installation and execution succeeds.
* `.zst` issue for Debian remains.

2022-09-30 13:29 UTC, nerdCopter approved these changes

2022-10-04 01:15 UTC, merged