Fix TPA
betaflight/betaflight-configurator pull request #3078
Opened 2022-11-10 02:12 UTC by haslinghuis

Include `tpa_mode` in msp and UI

2022-11-10 02:59 UTC, ctzsnooze commented
Tested! Works perfectly.
Fixes the problem where TPA values were incorrectly shown, and its great to be able to choose D or P&D options!
Thanks!

2022-11-10 02:59 UTC, ctzsnooze approved these changes

2022-11-10 03:50 UTC, sugaarK approved these changes

2022-11-10 05:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> PASS
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2022-11-10 09:37 UTC, Asizon requested changes

2022-11-10 11:57 UTC, haslinghuis commented on src/tabs/pid_tuning.html
> -                                <th i18n="pidTuningTPA"></th>
We also have tpa old class, reverted label for the old one.

2022-11-10 15:14 UTC, KarateBrot approved these changes

2022-11-14 00:20 UTC, ctzsnooze approved these changes

2022-11-14 04:12 UTC, blckmn approved these changes

2022-11-14 04:12 UTC, merged