repackage .deb with xz compression
betaflight/betaflight-configurator pull request #3157
Opened 2022-12-19 21:33 UTC by nerdCopter

* repackage ubuntu's .deb file as xz rather than zst
* ref: https://gist.github.com/goproslowyo/fe95c8e07c73593e2099687eeda78bc5
* fixes #3154 
* i'm not certain i like this approach, but it solves the problem -- i'll leave it to BF team to decide.

2022-12-19 21:45 UTC, nerdCopter commented
not correct yet, i'll work on it as time permits
![image](https://user-images.githubusercontent.com/56646290/208530155-bcfb690a-0aab-4558-9840-5fd8026190de.png)

2022-12-19 21:50 UTC, nerdCopter commented
oops, i was wrong 494MB is appropriate:
![image](https://user-images.githubusercontent.com/56646290/208530828-e956da15-2b5d-46f4-ba6d-6ba930a7ecea.png)


also, it works on `Debian 11`:
![image](https://user-images.githubusercontent.com/56646290/208530942-41cef480-5036-40ed-ae88-08f0a961031c.png)

2022-12-19 22:52 UTC, howels commented
@nerdCopter this occurs because Ubuntu has updated dpkg-deb to use zstd but Debian has not. Suggest that we could save time by simply running the build inside a Debian image instead of Ubuntu. This would then not require the slow recompression step.

2022-12-20 00:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2022-12-20 01:52 UTC, haslinghuis commented
@howels trying to get `gulp-debian` working locally. But maybe this might be of interest:

https://github.com/betaflight/betaflight-configurator/pull/3155#issuecomment-1358718000

2022-12-20 07:43 UTC, McGiverGim commented
> @nerdCopter this occurs because Ubuntu has updated dpkg-deb to use zstd but Debian has not. Suggest that we could save time by simply running the build inside a Debian image instead of Ubuntu. This would then not require the slow recompression step. Another alternative would be to alias `dpkg-deb` to `dpkg-deb -Zxz` in the shell used to build.

Github actions only have Ubuntu as image, at least that is what I see in the documentation.

2022-12-20 07:52 UTC, McGiverGim requested changes
I like this approach. We have one problem, and your solution (if it works) is a workaround, in one simple step, that we can add/remove easily in a future.
If we can't find another better option, this is ok to me.

2022-12-20 07:52 UTC, McGiverGim commented on .github/workflows/ci.yml
> +      - name: repack .deb file with xz compression
Simply add a comment here about why we are doing this. It will be easier for future developers when they see this code.

2022-12-20 07:52 UTC, McGiverGim commented on .github/workflows/ci.yml
> +        continue-on-error: false
I think `false` is the default value, so remove this line.

2022-12-20 15:34 UTC, McGiverGim approved these changes

2022-12-21 05:04 UTC, blckmn approved these changes

2022-12-21 05:04 UTC, merged