Enable dynamic notch warning
betaflight/betaflight-configurator pull request #3253
Opened 2023-01-16 18:15 UTC by haslinghuis

2023-01-16 22:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2023-01-16 22:59 UTC, KarateBrot requested changes
This is more of a suggestion to give it a shorter name

2023-01-16 22:59 UTC, KarateBrot commented on locales/en/messages.json
> +    "pidTuningDynamicNotchNyquistFilterDisabledWarning": {
```suggestion
    "pidTuningDynamicNotchFilterNyquistWarning": {
```

2023-01-16 22:59 UTC, KarateBrot commented on src/tabs/pid_tuning.html
> +                                        <p i18n="pidTuningDynamicNotchNyquistFilterDisabledWarning"></p>
```suggestion
                                        <p i18n="pidTuningDynamicNotchFilterNyquistWarning"></p>
```

2023-01-16 23:02 UTC, haslinghuis commented on locales/en/messages.json
> +    "pidTuningDynamicNotchNyquistFilterDisabledWarning": {
Done.

2023-01-16 23:02 UTC, haslinghuis commented on src/tabs/pid_tuning.html
> +                                        <p i18n="pidTuningDynamicNotchNyquistFilterDisabledWarning"></p>
Done.

2023-01-16 23:13 UTC, haslinghuis commented
![image](https://user-images.githubusercontent.com/8344830/212778528-374a3065-4adc-48ff-acf1-dccb78be2211.png)

2023-01-16 23:15 UTC, haslinghuis commented
After using a preset and arriving on the page we should adjust the message.
Otherwise we should enforce in firmware itself.

2023-01-17 01:55 UTC, haslinghuis commented
We are using tables in this tab for presentation. Tried margin but not getting expected results. Already spent too much time on presentation as we need to migrate to templates.

![image](https://user-images.githubusercontent.com/8344830/212792547-e06556b6-52f5-4233-ad4a-ffb0040636fd.png)

2023-01-17 03:30 UTC, KarateBrot approved these changes

2023-01-17 04:24 UTC, KarateBrot commented
> We are using tables in this tab for presentation. Tried margin but not getting expected results. Already spent too much time on presentation as we need to migrate to templates.

Looks pretty good anyway! 👌

2023-01-17 07:50 UTC, McGiverGim approved these changes

2023-01-17 12:27 UTC, merged