Fix MSDN browser
betaflight/betaflight-configurator pull request #3337
Opened 2023-02-10 23:23 UTC by haslinghuis

Fixes: #3336

Also MDSN browser in PortHandler is now disabled by default. Please use options tab to enable the feature.

2023-02-11 00:19 UTC, Schlaegel commented
This works for me!!!! W00H000! It's the first time 10.9 or 10.10 has worked. I tested it both with MDNS and without MDNS. Both worked. (The title is incorrectly labeled MSDN, which brings back memories of the Microsoft Developer Network and my career many decades ago.)

Thanks

2023-02-11 00:41 UTC, haslinghuis commented
Updated labels to mDSN

2023-02-11 00:54 UTC, Schlaegel commented
Almost. It's mDNS. Like regular DNS (Domain Name System) but with a lower case 'm' in front for multicast.

2023-02-11 01:17 UTC, haslinghuis commented
Fixed.

2023-02-11 03:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2023-02-11 17:33 UTC, nerdCopter approved these changes
* Although i cannot test any network/wifi, i verify that this does not break any USB usage. I can connect USB with the mDNS toggle `on` or `off`. (`Ubuntu 22.04.1 LTS`)

2023-02-15 07:01 UTC, chmelevskij commented on src/js/port_handler.js
> +            currentPorts = [ ...cp];
```suggestion
            currentPorts = cp;
```

2023-02-15 17:28 UTC, McGiverGim requested changes

2023-02-15 17:28 UTC, McGiverGim commented on src/js/tabs/options.js
> +options.initUseMdnsBrower = function() {
```suggestion
options.initUseMdnsBrowser = function() {
```

2023-02-15 17:28 UTC, McGiverGim commented on src/js/tabs/options.js
> +        TABS.options.initUseMdnsBrower();
```suggestion
        TABS.options.initUseMdnsBrowser();
```

2023-02-15 17:30 UTC, haslinghuis commented on src/js/tabs/options.js
> +options.initUseMdnsBrower = function() {
Good catch !

2023-02-15 17:32 UTC, haslinghuis commented on src/js/tabs/options.js
> +options.initUseMdnsBrower = function() {
Ah it worked because line 24

2023-02-15 17:34 UTC, haslinghuis commented on src/js/tabs/options.js
> +        TABS.options.initUseMdnsBrower();
Fixed!

2023-02-15 18:33 UTC, haslinghuis commented on src/js/port_handler.js
> +            currentPorts = [ ...cp];
Fixed!

2023-02-15 18:34 UTC, merged