Flasher tab: show commit field no matter what, if expert mode enabled
betaflight/betaflight-configurator pull request #3408
Opened 2023-04-07 04:16 UTC by limonspb

After this PR the "Select commit" text input will show up regardless (if in expert mode)
This will allow triggering cloud build API with make commands specifically for a certain branch/release on top of any PRs.

I think this change also requires Cloud build modification. I can see that request includes # commit:
![image](https://user-images.githubusercontent.com/2925027/230539408-ec3beab2-4e32-43a9-b911-85142a215192.png)

however, the build log does not reflect it:
https://build.betaflight.com/api/builds/24d611898699d3424bbbcdbc2a837ad3/log
https://build.betaflight.com/api/builds/24d611898699d3424bbbcdbc2a837ad3/json

2023-04-07 06:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2023-04-20 20:48 UTC, haslinghuis approved these changes

2023-04-21 01:23 UTC, limonspb commented
@haslinghuis don't merge plz, till @blckmn have a look. I think it requires some cloud-build changes.

2023-06-07 00:28 UTC, blckmn commented
I don't support this change. The commit dialogue is available for zulu "pre"-releases. Releases should not be modifiable.

2023-06-07 00:31 UTC, blckmn requested changes

2023-06-07 10:34 UTC, blckmn commented
We add a 4.4.3-zulu and after 4.4.3 release we add a 4.4.4-zulu and withdraw the 4.4.3-zulu

2023-06-07 10:42 UTC, limonspb commented
> We add a 4.4.3-zulu and after 4.4.3 release we add a 4.4.4-zulu and withdraw the 4.4.3-zulu



> We add a 4.4.3-zulu and after 4.4.3 release we add a 4.4.4-zulu and withdraw the 4.4.3-zulu
> 
> These are pinned to 4.4-maintenance like 4.5.0-zulu is currently pinned to master.

should we just always have 4.4-zulu so you don't have to manually change/add 4.4.2-zulu to 4.4.3-zulu etc?
For example, i wanted to test (https://github.com/betaflight/betaflight/pull/12866) but can't do it now because it's raised for 4.4-maintenance. So i tested the original PR against master, but the code is a bit different in master obviously.

2023-08-17 21:02 UTC, closed without merging