More feature tip at Configuration tab
betaflight/betaflight-configurator pull request #3413
Opened 2023-04-09 12:43 UTC by HThuren

Just add Help for some common used features

2023-04-09 14:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2023-04-09 21:21 UTC, haslinghuis requested changes

2023-04-09 21:21 UTC, haslinghuis commented on locales/en/messages.json
> +        "message": "Enable Sonar Ragefinder to measure distance to ground in cm"
Ragefinder :)

2023-04-09 21:21 UTC, haslinghuis commented on locales/en/messages.json
> +        "message": "Enable Telemetry output to send to transmitter"
telemetry lower case

2023-04-09 21:42 UTC, HThuren commented on locales/en/messages.json
> +        "message": "Enable Sonar Ragefinder to measure distance to ground in cm"
Angry sonar ... :-)

2023-04-09 21:45 UTC, haslinghuis commented on locales/en/messages.json
> +        "message": "Enable Sonar Ragefinder to measure distance to ground in cm"
:rofl:

2023-04-09 21:46 UTC, haslinghuis approved these changes

2023-04-12 13:07 UTC, nerdCopter approved these changes

2023-04-12 14:35 UTC, merged