Increased cloud build timeout to 75 seconds instead of 50
betaflight/betaflight-configurator pull request #3696
Opened 2023-12-26 03:37 UTC by limonspb

Seems like current cloud build timeout sometimes is no enough, because i keep sing this (sometimes):
![image](https://github.com/betaflight/betaflight-configurator/assets/2925027/422b1994-ea08-4a21-9b3c-a392723b126f)

This PR increases timeout to 75 seconds from 50 seconds.

2023-12-26 05:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> FAIL
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> FAIL
 - `Tested` label found -> FAIL
 - assigned to an approver -> FAIL
 - approver count at least three -> FAIL

2023-12-30 08:23 UTC, limonspb commented
Caught one more timeout error on build.
Looks like the cloud is busy sometimes, its not he build itself taking too long.
https://build.betaflight.com/api/builds/0c0159e30cf717c7ffd64ba6ae3eb0a7/log
![image](https://github.com/betaflight/betaflight-configurator/assets/2925027/c67500a8-a2e1-4161-a5be-8b5b98ae8675)

But since it's happening time to time, i think it's worth increasing timeout in Configurator.

2023-12-30 13:50 UTC, McGiverGim commented
Other build systems, like OpenWrt, show the position in the queue. In this way the user knows more or less the time to wait. I think it will be good to show this info in some way, or at least have two timeouts: one to advance in the queue and other for the build itself.

2023-12-31 07:06 UTC, limonspb commented
> Other build systems, like OpenWrt, show the position in the queue. In this way the user knows more or less the time to wait. I think it will be good to show this info in some way, or at least have two timeouts: one to advance in the queue and other for the build itself.

I think adding this new functionality at RC stage could be dangerous. Now this is a simple solution to mitigate most of the timeout issues, unless the queue is a little long.

2023-12-31 18:01 UTC, nerdCopter commented
https://build.betaflight.com/healthcheck shows the queue.
@blckmn controls the timeout on API side IIRC.

2024-01-05 20:05 UTC, ctzsnooze approved these changes

2024-01-05 20:21 UTC, haslinghuis commented
60 seconds :)

2024-01-05 22:14 UTC, haslinghuis commented on src/js/tabs/firmware_flasher.js
> +    maxCloudTries: 15,
Lets do 60 seconds :)

2024-01-05 22:26 UTC, haslinghuis commented on src/js/tabs/firmware_flasher.js
> +    maxCloudTries: 15,
Also don't get timeouts lately anymore.

2024-01-06 02:17 UTC, limonspb commented on src/js/tabs/firmware_flasher.js
> +    maxCloudTries: 15,
i think its already 60 now? I got timeout error just a few days ago

2024-01-06 21:09 UTC, blckmn commented
This is not the right way to go about it. It's by design that it times out and says retry. This gives you the option of exiting and doing something else. Making it 75 just prolongs this.

If the build server is busy you'll get a timeout. Retrying won't resubmit the job and double up because the API checks the queue for your build key, and just starts the wait process again.

This is just aesthetics.

Be better to wait indefinitely and give you a button to cancel the wait if you're really worried about the aesthetics.

2024-01-06 21:10 UTC, blckmn requested changes
As per comment. There are better options.

2024-01-07 01:26 UTC, closed without merging