Fix ol.css import
betaflight/betaflight-configurator pull request #3710
Opened 2023-12-30 18:58 UTC by haslinghuis

2023-12-30 20:17 UTC, blckmn commented
AUTOMERGE: (FAIL)
 - github identifies PR as mergeable -> FAIL
 - assigned to a milestone -> PASS
 - cooling off period lapsed -> FAIL
 - commit count less or equal to three -> PASS
 - `Don't merge` label NOT found -> PASS
 - at least one `RN:` label found -> PASS
 - `Tested` label found -> FAIL
 - assigned to an approver -> PASS
 - approver count at least three -> FAIL

2023-12-31 02:50 UTC, blckmn requested changes

2023-12-31 02:50 UTC, blckmn commented on gulpfile.js
> +    .src("./node_modules/ol/ol.css")
why remove the indentation?

2023-12-31 02:51 UTC, blckmn commented on gulpfile.js
> +    .pipe(gulp.dest(`${DIST_DIR}node_modules/ol`));
```suggestion
        .pipe(gulp.dest(`${DIST_DIR}node_modules/ol`));
```

2023-12-31 02:52 UTC, blckmn commented on gulpfile.js
> +    .src("./node_modules/ol/ol.css")
```suggestion
        .src("./node_modules/ol/ol.css")
```

2023-12-31 02:56 UTC, blckmn approved these changes

2023-12-31 02:59 UTC, haslinghuis commented
Applying https://github.com/betaflight/betaflight-configurator/pull/3196 would help

2023-12-31 07:17 UTC, chmelevskij requested changes
I’m pretty sure this will mess up web build.  Will fix tonight as I’ve had a stab at it recently

2023-12-31 15:31 UTC, haslinghuis commented
Closing in favor of #3711

2023-12-31 15:31 UTC, closed without merging