Add support for gyro_cal_on_first_arm
betaflight/betaflight-configurator pull request #3938
Opened 2024-05-06 20:28 UTC by haslinghuis

- Fixes #102 
- Support for disarm_kill_switch was removed in https://github.com/betaflight/betaflight/pull/5073
![image](https://github.com/betaflight/betaflight/assets/8344830/71fd9299-7aea-497e-9005-dd7d3217a27a)

2024-05-21 17:07 UTC, haslinghuis commented
Editor is happy to add vite imports all the time

![image](https://github.com/betaflight/betaflight/assets/8344830/ecdf37d2-7e6e-4f36-88aa-285ce8d1a216)

2024-05-22 10:58 UTC, KarateBrot requested changes

2024-05-22 10:58 UTC, KarateBrot commented on locales/en/messages.json
> +        "message": "Calibrate Gyro on first arm"
This change maybe gives a slightly better hint as to what is happening (= gyro gets calibrated before motors start to spin)
```suggestion
        "message": "Calibrate the gyro right before the first arm"
```

2024-05-22 11:06 UTC, KarateBrot approved these changes

2024-05-22 13:29 UTC, nerdCopter commented
my results are different, but this GPS enabled target has no actual GPS for testing.
![image](https://github.com/betaflight/betaflight-configurator/assets/56646290/f2bde37b-2431-4a1b-8541-24ddb2452946)

2024-05-22 13:33 UTC, haslinghuis commented
@nerdCopter Disarm motors after delay requires `MOTOR_STOP` feature (set in motor tab).

2024-05-22 13:44 UTC, nerdCopter commented
> @nerdCopter Disarm motors after delay requires `MOTOR_STOP` feature (set in motor tab).

probably also requires ESC and motors :laughing:  
_but my screenshot also shown no toggle switch on the GPS-Calibrate option_.

2024-05-22 13:47 UTC, haslinghuis commented
Yes checking here. Most have changed on rebase...

2024-05-22 14:30 UTC, nerdCopter commented
the above comment was
```
# version
# Betaflight / STM32F405 (S405) 4.6.0 May 21 2024 / 08:20:12 (32f1e9a17) MSP API: 1.46
# config rev: 93dfc69
# board: manufacturer_id: FOXE, board_name: FOXEERF405
```
did not test `#13626`

2024-05-22 14:47 UTC, merged