Fix MSP Radio emulator in PWA
betaflight/betaflight-configurator pull request #3939
Opened 2024-05-07 15:01 UTC by McGiverGim

This makes working again the MSP radio emulator under PWA.
With this changes, it works under PWA and under NW.js.

![image](https://github.com/betaflight/betaflight-configurator/assets/2673520/39e5da4a-d59f-4b04-88b0-555d398123a4)

BUT I've marked it as draft because under PWA only works with `yarn dev` but not under `yarn review`. I suspect it has something to do with https://vitejs.dev/guide/build#multi-page-app but I'm not sure. I tried to add this config to the code without luck. Some idea?

2024-05-07 18:00 UTC, McGiverGim commented
Added a new commit that fixes the issue with the "build" version of PWA. Now works, but maybe my solution is not good enough, but we can make it better with the reviews.

2024-05-07 18:42 UTC, chmelevskij commented on src/receiver_msp/index.html
there is not need really to rename this if we specify the input with `rollupOptions`

2024-05-07 18:44 UTC, chmelevskij approved these changes

2024-05-07 18:50 UTC, haslinghuis requested changes

2024-05-07 18:50 UTC, haslinghuis commented on src/receiver_msp/index.html
Not really a tab - could we rename it to `/receiver_msp.html` instead?

2024-05-07 19:05 UTC, McGiverGim commented
I tried but it didn't work. My first idea was to add it as subfolder inside the tabs one, and without renaming it, but it didn't work. Maybe I did something wrong, but I didn't found the problem.

2024-05-07 19:06 UTC, McGiverGim commented on src/receiver_msp/index.html
I tried but it didn't work. My first idea was to add it as subfolder inside the tabs one, and without renaming it, but it didn't work. Maybe I did something wrong, but I didn't found the problem.

2024-05-07 19:09 UTC, haslinghuis approved these changes
Possible have something to do with the `rollupOptions` used in Vite

2024-05-07 21:07 UTC, merged

2024-05-08 06:19 UTC, McGiverGim commented on src/receiver_msp/index.html
@haslinghuis it seems now it works, I don't know why yesterday don't. I will push a new PR renaming it.