Enforce preset mutally exclusive option groups
betaflight/betaflight-configurator pull request #3940
Opened 2024-05-08 03:09 UTC by Stampede10343

This enables presets that use the (Exclusive) directive on option groups to only allow a single item within that group to be checked at a time.

See [this PR](https://github.com/betaflight/firmware-presets/pull/461) on the presets repository for the indexer/verifier updates.

2024-05-12 07:18 UTC, McGiverGim commented
The first tests shows the window asking for the device to connect to, but after selecting it doesn't continue, so something is failing. I need to enable secure-context in local to do more tests.

2024-06-19 13:36 UTC, nerdCopter commented
Both PR's will need rebase if still in consideration.

2024-06-23 17:39 UTC, Stampede10343 commented
> Both PR's will need rebase on master if still in consideration.

Both PR's have been rebased

2024-06-23 18:20 UTC, haslinghuis requested changes

2024-06-23 18:20 UTC, haslinghuis commented on src/tabs/presets/DetailedDialog/PresetsDetailedDialog.js
> +        if(group.isExclusive) {
:space_invader: 

```suggestion
        if (group.isExclusive) {
```

2024-06-23 18:20 UTC, haslinghuis commented on src/tabs/presets/PresetsRepoIndexed/PresetParser.js
> +        if(isExclusiveGroup) {
:space_invader: 
```suggestion
        if (isExclusiveGroup) {
```

2024-07-10 19:31 UTC, haslinghuis commented
Any updates on testing @limonspb ?

2024-07-15 05:08 UTC, limonspb commented
> Any updates on testing @limonspb ?

Sorry for the delay.
Tested, works like a charm. Awesome job.

We probably need few more people, actual testers, to do some more resting.
This Configurator PR is fine. But the presets PR will be merged straight into production and all current configurator releases will start using the new thing. Thats why we prolly need few more people to test before merging presets PR.
@SupaflyFPV  @sugaarK :

could you plz test current configurator release with this preset source:
https://github.com/Stampede10343/firmware-presets/
Branch: develop

See if options in RC_LINK for example work like they did before.

Thanks!

2024-07-15 05:12 UTC, sugaarK commented
I need to see it in action to really get it!  will check out the branch

2024-07-15 05:18 UTC, sugaarK commented
> > Any updates on testing @limonspb ?
> 
> Sorry for the delay. Tested, works like a charm. Awesome job.
> 
> We probably need few more people, actual testers, to do some more testing. This Configurator PR is fine. But the presets PR will be merged straight into production and all current configurator releases will start using the new thing. Thats why we prolly need few more people to test before merging presets PR. @SupaflyFPV @sugaarK :
> 
> could you plz test current configurator release with this preset source: https://github.com/Stampede10343/firmware-presets/ Branch: develop
> 
> See if options in RC_LINK for example work like they did before, everything is applied normally etc.
> 
> Thanks!

what presets in this branch have it active?

2024-07-15 07:11 UTC, limonspb commented
> > > Any updates on testing @limonspb ?
> > 
> > 
> > Sorry for the delay. Tested, works like a charm. Awesome job.
> > We probably need few more people, actual testers, to do some more testing. This Configurator PR is fine. But the presets PR will be merged straight into production and all current configurator releases will start using the new thing. Thats why we prolly need few more people to test before merging presets PR. @SupaflyFPV @sugaarK :
> > could you plz test current configurator release with this preset source: https://github.com/Stampede10343/firmware-presets/ Branch: develop
> > See if options in RC_LINK for example work like they did before, everything is applied normally etc.
> > Thanks!
> 
> what presets in this branch have it active?

All RC link presets for example.
But the main thing to test is to make sure 10.9 and 10.10 releases are not going to break with the source `https://github.com/Stampede10343/firmware-presets/` `develop`.
So in current Configurator release the exclusive options are not going automatically deselect checkboxes, instead it should just show "exclusive" in the group name.
**Just need to test that the current Configurator release is not being broken with upcoming Presets repo change.**

2024-07-17 04:56 UTC, limonspb approved these changes

2024-07-17 06:34 UTC, haslinghuis approved these changes

2024-07-18 09:11 UTC, sugaarK approved these changes
works great

2024-07-18 09:14 UTC, merged

2024-12-23 08:15 UTC, limonspb commented
@Stampede10343 could you plz check this, something is going on i just noticed.
For example:
1. Open Karate Race 6S preset
2. select "new spice" like that:
![image](https://github.com/user-attachments/assets/e4f7adc1-59d6-49f1-a6f1-110f8b51817a)
3. Click on "Tracer/ERLS 250hz".
This will disable "new spice", so you will see this:
![image](https://github.com/user-attachments/assets/fd5a9fa2-5359-49ca-9574-e8da9dffcd54)

plus seems like options without option groups are not contributing to the result CLI