Use the "show manual" preference in the porthandler to show or hide the option
betaflight/betaflight-configurator pull request #3968
Opened 2024-05-17 11:37 UTC by McGiverGim

Right now the manual port is always shown. This PR does some things:
- Makes the ports combo respect the show manual or not option
- Adds a default "Select your device" disabled option to the list of ports, and is the default one when there is no other ports in the list.
- With each change, first, tries to select a "real" one port, if not exists the "virtual" and then the "manual". As last option it defaults to "Select your device".

The port handler needs a bigger refactor, this are only the first steps.

2024-05-17 14:35 UTC, nerdCopter approved these changes

2024-05-17 14:51 UTC, haslinghuis approved these changes

2024-05-17 16:32 UTC, chmelevskij commented
This breaks current config and virtual mode sync with the config screen. Only visible in initial load when settings are still not set.
![image](https://github.com/betaflight/betaflight-configurator/assets/7774918/c4eb4c05-c296-43e6-977e-6b9f4d719096)

2024-05-17 16:32 UTC, chmelevskij requested changes
virtual mode option is out of sync with the toggle on the first load of the app

2024-05-17 19:20 UTC, McGiverGim commented
I will check it again when I rebase the code of the lint PR. Thanks for testing!

2024-05-21 06:15 UTC, McGiverGim commented
Rebased and ready to merge.

2024-05-23 14:57 UTC, McGiverGim commented
Rebased against master.

2024-05-23 15:10 UTC, merged