Keep only browser clipboard
betaflight/betaflight-configurator pull request #3999
Opened 2024-06-02 06:09 UTC by chmelevskij

remove unused nwjs an cordova clipboard apis

2024-06-02 21:44 UTC, haslinghuis approved these changes

2024-06-03 08:18 UTC, McGiverGim requested changes

2024-06-23 20:04 UTC, haslinghuis commented on src/js/Clipboard.js
> +        this.writeAvailable = false;
```suggestion
```

2024-07-10 19:29 UTC, haslinghuis commented
Already implemented in https://github.com/betaflight/betaflight-configurator/pull/3998

2024-07-10 19:29 UTC, closed without merging