Warn when selected rx protocol is not in build configuration
betaflight/betaflight-configurator pull request #4150
Opened 2024-09-02 20:33 UTC by her01n

User can select a receiver protocol when upgrading the firmware. Later, the protocol can be selected in the receiver tab. Only the protocol selected at the firmware upgrade time would work. Let's warn the user if the protocol selected in the receiver tab will not work.

2024-09-02 20:43 UTC, haslinghuis commented
Instead of a warning unavailable rx protocols should be hidden.

2024-09-03 12:30 UTC, her01n commented
Unsupported rx protocols are disabled. I have retained the warning - it may be displayed when wrong protocol is already selected by previous configurator version.

2024-09-03 12:37 UTC, haslinghuis commented
![image](https://github.com/user-attachments/assets/4b3a7757-9800-4404-b916-8e92a8d07cd9)

2024-09-03 12:42 UTC, haslinghuis approved these changes
LGTM

2024-09-03 13:16 UTC, nerdCopter commented
good work!
why would `target_custom` be enabled is i flashed only CRSF?
![image](https://github.com/user-attachments/assets/27b26f5d-39f4-4bdc-9549-c36736752ee5)

2024-09-03 13:25 UTC, nerdCopter commented
looks good with a few multiple protocols added as well
![image](https://github.com/user-attachments/assets/f0b8a321-58db-4eee-927e-cf4a1f604428)

i just need to know why `target_custom` is available, or if it is to be expected before i approve.

2024-09-03 13:55 UTC, her01n commented
TARGET_CUSTOM has no corresponding build option, as listed in src/js/fc.js:72. I guess it is always available.

2024-09-03 14:00 UTC, haslinghuis commented
There exists `USE_SERIALRX_TARGET_CUSTOM`, so prefer this be handled like other cases as it probably is to be used as custom define anyway.

2024-09-03 15:23 UTC, nerdCopter requested changes

2024-09-03 15:23 UTC, nerdCopter commented on src/js/fc.js
> +            let supportedRxTypes = ['NONE', 'TARGET_CUSTOM'];
```suggestion
            let supportedRxTypes = ['NONE',];
            if (options.includes('USE_SERIALRX_TARGET_CUSTOM')) {
                supportedRxTypes.push('TARGET_CUSTOM');
            }  
```

2024-09-03 15:23 UTC, nerdCopter commented on src/js/fc.js
> +            let supportedRxTypes = ['NONE', 'TARGET_CUSTOM'];
@haslinghuis , please verify, TY.

2024-09-03 15:43 UTC, haslinghuis commented
![image](https://github.com/user-attachments/assets/9e0dcb03-f653-4149-a916-3776345438d3)

2024-09-03 15:51 UTC, nerdCopter approved these changes

2024-09-03 17:54 UTC, merged

2024-10-02 13:03 UTC, nerdCopter commented
i just noticed if a pilot pastes a `diff` that contains a non-active protocol, the UI still shows the configured protocol in normal font shade (black here).
i wonder if there is a way to dimm (gray) the set protocol if the user did not cloud-build them.

e.g. i built the firmware with CRSF, but the quad is SBUS, i pasted my diff and went to the receiver tab to see the SBUS settings in normal color even though the firmware does not contain SBUS.  yes, user-error, but maybe a mitigable situation.
![image](https://github.com/user-attachments/assets/b6096a9b-cb93-45c8-b1e2-4d7d1bdf0b6b)

2024-10-02 14:06 UTC, haslinghuis commented
- think this should be fixed at the source (firmware).

![image](https://github.com/user-attachments/assets/03179ffc-41a3-48c1-a144-4b698d587911)

- alternative is to set to NONE when invalid provider is used.

![image](https://github.com/user-attachments/assets/60750319-440f-477e-93a0-1d79fd9f5327)

2024-10-02 14:13 UTC, nerdCopter commented
It does already says `not supported` but my eyes skipped over such.  Either way is fine to me. Seemingly a dimm font would be a good visual-note and maybe easy to factor. :man_shrugging:.
In this case, I happened to wonder why RX/TX was not working, then realized why (i'm accustomed to CRSF now).  I commented because i think other pilots might experience same as well.
Of course this idea is not all that important at all.

2024-10-02 14:15 UTC, nerdCopter commented
It does already says `not supported` but my eyes skipped over such.  Either way is fine to me. Seemingly a dimm font would be a good visual-note and maybe easy to factor. :man_shrugging:.
In this case, I happened to wonder why RX/TX was not working, then realized why (i'm accustomed to CRSF now).  I commented because i think other pilots might experience same as well.
Of course this idea is not all that important at all.

edit: occurs to me that #2 (`NONE`) might not accurately reflect is CLI setting.

2024-10-02 14:31 UTC, haslinghuis commented
![image](https://github.com/user-attachments/assets/5cdf8573-892b-4261-88ef-361088c2863e)