hover point throttle curve adjustment
betaflight/betaflight-configurator pull request #4245
Opened 2024-11-08 19:14 UTC by marc-frank

- added input for value adjustment
- added text to locales
- adjusted throttle curve math to take hover point into account

Hi, I'd like to propose a new feature / change to an existing feature: setting the hover point of a quad to 50% of the throttle stick range.

I have been using subtrim in EdgeTX in center only mode to achieve this already, but it is a quad specific setting which I'd like to have in Betaflight.

Setting the hover point to 50% stick travel gives you a lot more "resolution" between 0 throttle and the hover point, therefore making flying at lower throttle in tight spaces a lot easier.

https://discord.com/channels/868013470023548938/1303071076342956072

https://github.com/user-attachments/assets/d0d4d1c4-afed-4889-b8ca-b7319125f966

2024-11-08 19:21 UTC, haslinghuis commented
There is no need to add translations beside `EN` language messages. Other languages will be translated using crowdin.

2024-11-08 20:06 UTC, marc-frank commented
Oh okay, sorry. Should I remove the other ones?

2024-11-08 23:53 UTC, haslinghuis requested changes

2024-11-08 23:53 UTC, haslinghuis commented on src/js/tabs/pid_tuning.js
> +        $('.throttle input[name="hover"]').val(FC.throttle_HOVER.toFixed(2));
FC.THROTTLE_HOVER should be a member of some PG to be decided in firmware.

2024-12-09 13:05 UTC, OGCJM11 approved these changes

2025-01-09 12:45 UTC, haslinghuis commented on src/js/tabs/pid_tuning.js
> +        $('.throttle input[name="hover"]').val(FC.throttle_HOVER.toFixed(2));
If you want to use `FC.RC_TUNING.throttle_HOVER` it should be added to firmware MSP message.

2025-01-15 13:47 UTC, nerdCopter commented
@marc-frank , if it it not clear, please understand if you wish to achieve this feature, the firmware must be modified as well as previously stated by @haslinghuis .

@bw1129, @ChrisRosser , any thoughts on this feature?

2025-01-15 14:47 UTC, ChrisRosser commented
> @bw1129, @ChrisRosser , any thoughts on this feature?

I think it's a natural extension of the control we have over throttle feel right now.

Throttle MID and EXPO allow fine resolution around the hover point but don't allow you to control where the hover point is in terms of stick travel. This feature accomplishes that.  I don't like the way it creates a discontinuity in the throttle curve.

I think modifying the underlying throttle curve as a bezier with HOVER POINT would give the same effect without a discontinuity of gradient. MID and EXPO could then work on that bezier curve to add expo.

2025-01-15 15:03 UTC, bw1129 commented
> @bw1129, @ChrisRosser , any thoughts on this feature?

I really like this! As Chris said, a natural extension/improvement to what's there.

2025-01-16 12:14 UTC, ChrisRosser commented
Here is a simple example of how to make Hoverpoint smooth.
[Throttle curve.xlsx](https://github.com/user-attachments/files/18439354/Throttle.curve.xlsx)

2025-01-16 12:53 UTC, marc-frank commented
> Here is a simple example of how to make Hoverpoint smooth. [Throttle curve.xlsx](https://github.com/user-attachments/files/18439354/Throttle.curve.xlsx)

that looks nice. another good way to do it 
but have you tried emulating the the throttle curve with dicontinuity in the radio? it's really not that bad.

1. everything default
2. fly and find hover point percentage
3. land, bring throttle stick to 50%
4. edit subtrim in center only mode until osd th% shows the hover %

2025-02-01 14:49 UTC, marc-frank commented
Just created a fw pull request
https://github.com/betaflight/betaflight/pull/14229

2025-02-03 20:12 UTC, nerdCopter commented
another note: do not update package.json/yarn.lock in a feature PR.

2025-02-03 20:31 UTC, nerdCopter commented
fix is force-pushed.
apologies, but it was easiest to squash the rebase.
please verify code as expected. (you may have to delete your local branch and pull.)

2025-02-03 21:15 UTC, marc-frank commented
works fine here and all my changes seem to be there, too
there is some error message when i try to open the hover-point branch in the fw repo, sent you an email

2025-02-03 21:16 UTC, nerdCopter commented
anyone knowledgeable about Github-Desktop GUI?  @marc-frank has this error. I suggested deleting local ./src/config , but i am not certain.
![image](https://github.com/user-attachments/assets/ce889e3f-163a-4fc9-91cc-f1b036ab77ea)

https://github.com/user-attachments/assets/550bf51a-5de0-49b9-93a5-1a1ffef1ac88

2025-02-03 21:47 UTC, marc-frank commented
i redid the cloning and branch switch with the git bash cli and now it's all fine

2025-02-03 22:02 UTC, haslinghuis approved these changes

2025-02-04 14:26 UTC, nerdCopter requested changes
will need to accommodate the requested changes of the firmware.

2025-03-22 14:44 UTC, marc-frank commented
https://github.com/user-attachments/assets/5752b196-509a-4800-8beb-d45d22a65eca

with the parameter now being read and written via msp it actually works in the configurator. the same value is shown again after diconnect reconnect! a success 🎉

sadly the osd still shows 50% throttle at 50% stick position, despite hover being set to 25%
but idk if that's what's supposed to happen (showing stick position instead of throttle curve output %)

2025-03-22 15:08 UTC, marc-frank commented
just did a test flight, works beautifully :)
babytooth hovers at 25% so i set hover to 25% and it now hovers at 50% throttle stick

2025-03-24 14:58 UTC, nerdCopter commented
please keep the this and the firmware PR's updated (rebased on master).

2025-03-26 18:22 UTC, nerdCopter commented on src/js/fc.js
> +            throttle_HOVER: 0,
i this position good @haslinghuis ? seems to not need match position with firmware correct?

2025-03-26 18:30 UTC, haslinghuis commented on src/js/fc.js
> +            throttle_HOVER: 0,
Yes guess it should be moved after `rates_type: 0`

![image](https://github.com/user-attachments/assets/211a4855-f222-4415-a259-27e47b940a84)

2025-04-01 18:33 UTC, nerdCopter commented on src/js/fc.js
> +            throttle_HOVER: 0,
@marc-frank :arrow_up:

2025-04-01 19:23 UTC, marc-frank commented on src/js/fc.js
> +            throttle_HOVER: 0,
sorry i should do these changes more quickly, right? also rebased again. didn't you say something about reducing the pr to a single commit? what is that called? "Squash and merge into current branch"?

2025-04-01 20:38 UTC, nerdCopter commented
thank you @marc-frank , 
request retesting with most recent modification.
@haslinghuis has asked internal devs in Discord to review these PR's.

2025-04-10 13:48 UTC, nerdCopter approved these changes
- approving untested as firmware is merged.

2025-04-10 13:50 UTC, merged