Enforce OSD option
betaflight/betaflight-configurator pull request #4251
Opened 2024-11-17 20:49 UTC by haslinghuis

Lots of issues reported with users not reading release notes so decided to enforce OSD option.

![image](https://github.com/user-attachments/assets/a01d3227-1392-4415-a75e-a9e7cf9bd4f4)

2024-11-17 20:53 UTC, VitroidFPV commented
For the wording: as this is meant to be a beginner-accessible feature (most people have no clue what a "MAX7456" is), maybe just Digital and Analog? Other than that, looks great

2024-11-17 21:27 UTC, VitroidFPV approved these changes

2024-11-17 21:36 UTC, VitroidFPV approved these changes

2024-11-18 00:15 UTC, blckmn requested changes

2024-11-18 00:15 UTC, blckmn commented on src/js/tabs/firmware_flasher.js
> +            data.generalOptions = data.generalOptions.filter(option => option.value !== 'USE_FRSKYOSD' && option.value !== 'USE_OSD_SD' && option.value !== 'USE_OSD_HD');
```suggestion
            data.generalOptions = data.generalOptions.filter(option => !option.group);
```

2024-11-18 00:15 UTC, blckmn commented on src/js/tabs/firmware_flasher.js
> +            data.osdProtocols = [
```suggestion
            data.osdProtocols = data.generalOptions.filter(option => option.group === 'OSD');
```

2024-11-18 00:15 UTC, blckmn commented on src/js/tabs/firmware_flasher.js
> +            data.osdProtocols = [
You can map to a new item, using the groupedName if you want to change the name to a different name.

2024-11-18 00:16 UTC, blckmn commented on src/js/tabs/firmware_flasher.js
> +            data.osdProtocols = [
https://build.betaflight.com/api/options

2024-11-18 01:58 UTC, blckmn commented on src/js/tabs/firmware_flasher.js
> +            data.osdProtocols = [
you will also need to cater for the "none" option... so maybe a helper function to add this, and map. note the none option should have an empty value.

2024-11-18 13:59 UTC, nerdCopter commented
`8dd138ce`
![image](https://github.com/user-attachments/assets/6090d288-7b2e-42e7-a1db-8023d257791a)

2024-11-18 14:04 UTC, haslinghuis commented
@nerdCopter do you have more info on what kind of build? Works with cloud build target

2024-11-18 14:11 UTC, nerdCopter commented
`0f54217e` works
![image](https://github.com/user-attachments/assets/fcfa1f3d-2b96-4ddb-a501-5f4d7f3049a0)

word `Analogue` is incorrect, should be `Analog`

opinion: I feel that `Analog` or `Digital` should be default, not `None`.

2024-11-18 14:16 UTC, haslinghuis commented
@nerdCopter 

> word Analogue is incorrect, should be Analog

That is how it is named in cloud build API.

> opinion: I feel that Analog or Digital should be default, not None.

None is only selected if analog, digital, frsky is not present.

2024-11-18 14:21 UTC, nerdCopter commented
> That is how it is named in cloud build API.

https://www.merriam-webster.com/dictionary/analogue  versus https://www.merriam-webster.com/dictionary/analog.  okay, i thin it is British English vs American English issue.

> None is only selected if analog, digital, frsky is not present.

fair, i only saw loading screen , no FC.

2024-11-18 19:42 UTC, blckmn commented
> > That is how it is named in cloud build API.
> 
> https://www.merriam-webster.com/dictionary/analogue versus https://www.merriam-webster.com/dictionary/analog. i think it is British English vs American English issue.
> 
> > None is only selected if analog, digital, frsky is not present.
> 
> fair, i only saw loading screen , no FC.

I have updated this to be "american". It will flow through in an hour or so. 

I does however raise a good point. We should localise these display values. We can do so by adding the american version into the messages.json as a key, and then adding the localisation after request to API. This would allow for crowdin to do the work. However we could also consider adding the localisation to the API based on the language setting provided in the header.

2024-11-18 19:45 UTC, blckmn approved these changes

2024-11-18 20:05 UTC, nerdCopter approved these changes

2024-11-18 20:35 UTC, merged